# $<Schema>$ https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
path_classifiers:
  generated:
    - "compiled/*"
  documentation: []
  library:
    - "**/node_modules/*"
    - "**/thirdparty/lib/*"
  template:
    - "reference/*"
  test:
    - "**/*debug*.*"
    - "**/*deprecated*.*"
    - "**/*test*.*"
    - "**/debug/*"
    - "**/deprecated/*"
    - "**/test/*"
queries:
  - include: "*"
extraction:
  javascript:
    index:
      filetypes:
        ".jsm": "js"
        ".mjs": "js"
        ".tmpl": "html"
        ".yml": "yaml"
      filters:
        - include: "**/*.ts"
      typescript: "full"
      xml_mode: "all"
