# $<Schema>$ https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
extraction:
  javascript:
    index:
      filetypes:
        ".cjs": "js"
        ".jsm": "js"
        ".mjs": "js"
        ".tmpl": "html"
        ".yml": "yaml"
      filters:
        - include: "**/*.ts"
      typescript: "full"
      xml_mode: "all"
queries:
  - include: "*"
