# $<Schema>$ https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[Docker]"
    labels:
      - "Platform/Docker 🐳"
      - "Status/Pending 🔵"
      - "Type/Dependency 📦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[Git Submodule]"
    labels:
      - "Status/Pending 🔵"
      - "Type/Dependency 📦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[GitHub Actions]"
    labels:
      - "Platform/GitHub/Actions :octocat:"
      - "Status/Pending 🔵"
      - "Type/Dependency 📦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[NPM]"
    labels:
      - "Platform/NodeJS 🔘"
      - "Status/Pending 🔵"
      - "Type/Dependency 📦"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
    versioning-strategy: "increase"
