name: "Analyze Code - Open Source Static Analysis Runner"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
jobs:
  analyze-code-ossar:
    name: "Analyze Code - Open Source Static Analysis Runner"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      # Ensure a compatible version of .NET is installed.
      - name: "Install .NET"
        uses: "actions/setup-dotnet@v2.0.0"
        with:
          dotnet-version: "6.x.x"
      - name: "Analyze Repository"
        id: "ossar"
        uses: "github/ossar-action@v1.1.0"
      - name: "Upload Result"
        uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: "${{steps.ossar.outputs.sarifFile}}"
