# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Anti Virus - ClamAV (Full)"
on:
  workflow_dispatch:
jobs:
  anti-virus-clamav-full:
    name: "Anti Virus - ClamAV (Full)"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
        with:
          fetch-depth: 0
      - name: "Full Scan Repository"
        uses: "djdefi/gitavscan@4"
        with:
          full: "--full"
