# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Check Deno Dependencies"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/check-deno-dependencies.yml@main"
