# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "CI/CD - Deno"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * SUN"
    - cron: "0 12 * * WED"
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/cicd-deno.yml@main"
