# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Code Review - Deno"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * SUN"
    - cron: "0 12 * * WED"
  workflow_dispatch:
jobs:
  main:
    name: "${{matrix.runs-on}}"
    strategy:
      matrix:
        runs-on:
          - "ubuntu-latest"
      fail-fast: false
    uses: "hugoalh/hugoalh/.github/workflows/reusable-code-review-deno-1.yml@main"
    with:
      runs-on: "${{matrix.runs-on}}"
