# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "New Release Announcer - IFTTT"
on:
  release:
    types:
      - "published"
jobs:
  new-release-announcer-ifttt:
    name: "New Release Announcer - IFTTT"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/trigger-ifttt-webhook-applet-ghaction@v4.0.0-beta.4"
        with:
          webhook_eventname: "githubaction_twitter"
          webhook_key: "${{secrets.IFTTTWEBHOOK_HUGOALH_KEY}}"
          value1: "Hello, world!"
