# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "NodeJS - Publish - NPM"
on:
  release:
    types:
      - "published"
permissions:
  contents: "write"
  id-token: "write"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/call-nodejs-publish-npm-0.yml@main"
    secrets:
      NPM_TOKEN: "${{secrets.NPM_TOKEN}}"
