# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Publish - GitHub Packages - NodeJS"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "{string} Tag without prefix `v`."
        required: true
jobs:
  publish-ghp-nodejs:
    name: "Publish - GitHub Packages - NodeJS"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.4.0"
        with:
          ref: "v${{github.event.inputs.tag}}"
      - name: "Correct Package Name"
        run: |
          [string]$PackageContent = Get-Content -Encoding utf8NoBOM -Path .\package.json -Raw
          Set-Content -Encoding utf8NoBOM -Path .\package.json -Value $($PackageContent -replace $(ConvertFrom-Json -InputObject $PackageContent).name, "@${{github.repository}}")
        shell: "pwsh"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.5.1"
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://npm.pkg.github.com/"
      - name: "Publish"
        run: "npm publish"
        env:
          NODE_AUTH_TOKEN: "${{github.token}}"
