name: "Publish - GitHub Packages - NodeJS"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "{string} Tag without prefix `v`."
        required: true
jobs:
  publish-ghp-nodejs:
    name: "Publish - GitHub Packages - NodeJS"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          ref: "v${{github.event.inputs.tag}}"
      - name: "Correct Package Name"
        run: |
          [String]$PackageContent = Get-Content -Path '.\package.json' -Raw -Encoding 'UTF8NoBOM'
          Set-Content -Path '.\package.json' -Value ($PackageContent -ireplace (ConvertFrom-Json -InputObject $PackageContent).name, "@${{github.repository}}") -NoNewLine -Encoding 'UTF8NoBOM' -Confirm:$False
        shell: "pwsh"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v3.4.1"
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://npm.pkg.github.com/"
      - name: "Publish"
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: "${{github.token}}"
