# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Publish - GitHub Packages For NodeJS"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag without prefix `v`."
        required: true
jobs:
  publish-ghp-nodejs:
    name: "Publish - GitHub Packages For NodeJS"
    if: "${{github.actor == 'hugoalh'}}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.5"
        with:
          ref: "v${{github.event.inputs.tag}}"
      - name: "Correct Package Name"
        run: |
          $packageContent = (Get-Content -Path .\package.json -Encoding utf8NoBOM -Raw)
          $packageOriginalName = (ConvertFrom-Json -InputObject $packageContent | Select-Object -ExpandProperty name)
          Set-Content -Path .\package.json -Value "$(($packageContent).Replace($packageOriginalName, "@${{github.repository}}"))" -Encoding utf8NoBOM
        shell: "pwsh"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.4.1"
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://npm.pkg.github.com/"
      - name: "Publish"
        run: "npm publish"
        env:
          NODE_AUTH_TOKEN: "${{github.token}}"
