name: "Publish PowerShell Module - PowerShell Gallery"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  publish-powershell-module-psg:
    uses: "hugoalh/hugoalh/.github/workflows/publish-powershell-module-psg.yml@main"
    secrets: "inherit"
