name: "Publish NodeJS Package - NPM"
on:
  release:
    types:
      - "published"
defaults:
  run:
    shell: "pwsh"
jobs:
  publish-nodejs-package-npm:
    uses: "hugoalh/hugoalh/.github/workflows/publish-nodejs-package-npm.yml@main"
    secrets: "inherit"
