# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish NodeJS Package - NPM"
on:
  release:
    types:
      - "published"
defaults:
  run:
    shell: "pwsh"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/reusable-publish-nodejs-package-npm.yml@main"
    secrets:
      NPM_TOKEN: "${{secrets.NPM_TOKEN}}"
