# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Sync Label"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/label.yml"
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/sync-label.yml@main"
