name: "Verify Deno Dependencies"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/verify-deno-dependencies.yml@main"
