# yaml-language-server: $schema=https://hugoalh.github.io/schema/json/sdvcfs-labels.json

#MARK: Platforms
- name: "* Alpine"
  color: "#0D597F"
  description: "Related to Alpine."
  aliases:
    - "Platform/LinuxAlpine"
- name: "* Android"
  color: "#3DDC84"
  description: "Related to Android."
  aliases:
    - "Platform/Android"
- name: "* Bluesky"
  color: "#0285FF"
  description: "Related to Bluesky."
  aliases:
    - "Platform/Bluesky"
- name: "* Bun"
  color: "#F9F1E1"
  description: "Related to Bun."
  aliases:
    - "Platform/Bun"
- name: "* ClamAV"
  color: "#B83033"
  description: "Related to ClamAV."
  aliases:
    - "Platform/ClamAV"
- name: "* CloudflareWorkers"
  color: "#F38020"
  description: "Related to Cloudflare Workers."
  aliases:
    - "Platform/CloudflareWorkers"
- name: "* CodeQL"
  color: "#FFFFFF"
  description: "Related to CodeQL."
  aliases:
    - "Platform/CodeQL"
- name: "* Crowdin"
  color: "#2E3340"
  description: "Related to Crowdin."
  aliases:
    - "Platform/Crowdin"
- name: "* Dart"
  color: "#0175C2"
  description: "Related to Dart."
- name: "* Debian"
  color: "#A81D33"
  description: "Related to Debian."
  aliases:
    - "Platform/LinuxDebian"
- name: "* Deno"
  color: "#000000"
  description: "Related to Deno."
  aliases:
    - "Platform/Deno"
- name: "* DenoNetwork"
  color: "#000000"
  description: "Related to Deno Deploy, Deno Land, or Deno Module Registry."
  aliases:
    - "Platform/DenoNetwork"
- name: "* Dependabot"
  color: "#025E8C"
  description: "Related to Dependabot."
  aliases:
    - "Platform/Dependabot"
- name: "* Discord"
  color: "#5865F2"
  description: "Related to Discord."
  aliases:
    - "Platform/Discord"
- name: "* Docker"
  color: "#2496ED"
  description: "Related to Docker."
  aliases:
    - "Platform/Docker"
- name: "* DotNet"
  color: "#512BD4"
  description: "Related to .NET."
  aliases:
    - "Platform/DotNet"
- name: "* FDroid"
  color: "#1976D2"
  description: "Related to F-Droid."
- name: "* Flutter"
  color: "#02569B"
  description: "Related to Flutter."
- name: "* Git"
  color: "#F05032"
  description: "Related to Git."
  aliases:
    - "Platform/Git"
- name: "* GitHub"
  color: "#181717"
  description: "Related to GitHub."
  aliases:
    - "Platform/GitHub"
- name: "* GitHubActions"
  color: "#2088FF"
  description: "Related to GitHub Actions."
  aliases:
    - "Platform/GitHubActions"
- name: "* GitHubPackages"
  color: "#181717"
  description: "Related to GitHub Packages."
  aliases:
    - "Platform/GitHubPackages"
- name: "* GitHubPages"
  color: "#222222"
  description: "Related to GitHub Pages."
  aliases:
    - "Platform/GitHubPages"
- name: "* GitLFS"
  color: "#F64935"
  description: "Related to Git LFS."
  aliases:
    - "Platform/GitLFS"
- name: "* Godot"
  color: "#478CBF"
  description: "Related to Godot."
  aliases:
    - "Platform/Godot"
- name: "* Google"
  color: "#4285F4"
  description: "Related to Google."
- name: "* GoogleChrome"
  color: "#4285F4"
  description: "Related to Google Chrome."
  aliases:
    - "Platform/GoogleChrome"
- name: "* GooglePlay"
  color: "#414141"
  description: "Related to Google Play."
- name: "* Guilded"
  color: "#F5C400"
  description: "Related to Guilded."
  aliases:
    - "Platform/Guilded"
- name: "* JavaScript"
  color: "#F7DF1E"
  description: "Related to JavaScript."
  aliases:
    - "Platform/JavaScript"
- name: "* JSR"
  color: "#F7DF1E"
  description: "Related to JSR (JavaScript Registry)."
  aliases:
    - "Platform/JSR"
- name: "* Linux"
  color: "#FCC624"
  description: "Related to Linux."
  aliases:
    - "Platform/Linux"
- name: "* MacOS"
  color: "#000000"
  description: "Related to MacOS."
  aliases:
    - "Platform/AppleOS"
    - "Platform/MacOS"
- name: "* Mastodon"
  color: "#6364FF"
  description: "Related to Mastodon."
  aliases:
    - "Platform/Mastodon"
- name: "* MicrosoftAzure"
  color: "#0078D4"
  description: "Related to Microsoft Azure."
  aliases:
    - "Platform/MicrosoftAzure"
- name: "* MicrosoftEdge"
  color: "#0078D7"
  description: "Related to Microsoft Edge."
  aliases:
    - "Platform/MicrosoftEdge"
- name: "* Minecraft"
  color: "#62B47A"
  description: "Related to Minecraft (Bedrock)."
  aliases:
    - "Platform/Minecraft"
- name: "* MinecraftJava"
  color: "#62B47A"
  description: "Related to Minecraft Java."
  aliases:
    - "Platform/MinecraftJava"
- name: "* NodeJS"
  color: "#339933"
  description: "Related to NodeJS."
  aliases:
    - "Platform/NodeJS"
- name: "* NPM"
  color: "#CB3837"
  description: "Related to NPM."
  aliases:
    - "Platform/NPM"
- name: "* PowerShell"
  color: "#5391FE"
  description: "Related to PowerShell."
  aliases:
    - "Platform/PowerShell"
- name: "* PowerShellGallery"
  color: "#5391FE"
  description: "Related to PowerShell Gallery."
  aliases:
    - "Platform/PowerShellGallery"
- name: "* Python"
  color: "#3776AB"
  description: "Related to Python."
  aliases:
    - "Platform/Python"
- name: "* RevoltChat"
  color: "#FF4655"
  description: "Related to Revolt Chat."
  aliases:
    - "Platform/RevoltChat"
- name: "* Roblox"
  color: "#000000"
  description: "Related to Roblox."
  aliases:
    - "Platform/Roblox"
- name: "* RobloxStudio"
  color: "#00A2FF"
  description: "Related to Roblox Studio."
  aliases:
    - "Platform/RobloxStudio"
- name: "* Rust"
  color: "#000000"
  description: "Related to Rust."
  aliases:
    - "Platform/Rust"
- name: "* Steam"
  color: "#000000"
  description: "Related to Steam."
- name: "* Telegram"
  color: "#26A5E4"
  description: "Related to Telegram."
  aliases:
    - "Platform/Telegram"
- name: "* TypeScript"
  color: "#3178C6"
  description: "Related to TypeScript."
  aliases:
    - "Platform/TypeScript"
- name: "* Ubuntu"
  color: "#E95420"
  description: "Related to Ubuntu."
  aliases:
    - "Platform/LinuxUbuntu"
- name: "* VisualStudio"
  color: "#5C2D91"
  description: "Related to Visual Studio."
  aliases:
    - "Platform/VisualStudio"
- name: "* VisualStudioCode"
  color: "#007ACC"
  description: "Related to Visual Studio Code."
  aliases:
    - "Platform/VisualStudioCode"
- name: "* VisualStudioMarketplace"
  color: "#CB2E6D"
  description: "Related to Visual Studio Marketplace."
  aliases:
    - "Platform/VisualStudioMarketplace"
- name: "* Weblate"
  color: "#2ECCAA"
  description: "Related to Weblate."
  aliases:
    - "Platform/Weblate"
- name: "* Windows"
  color: "#0078D4"
  description: "Related to Windows."
  aliases:
    - "Platform/Windows"
- name: "* YARA"
  color: "#808080"
  description: "Related to YARA."

#MARK: Priorities
- name: "🔴 High"
  color: "#F44336"
  description: "This is high priority."
  aliases:
    - "Priority/High 🔴"
- name: "🟢 Low"
  color: "#4CAF50"
  description: "This is low priority."
  aliases:
    - "Priority/Low 🟢"
- name: "🟡 Medium"
  color: "#FFEB3B"
  description: "This is medium priority."
  aliases:
    - "Priority/Medium 🟡"
- name: "🚨 Urgent"
  color: "#D50000"
  description: "This is urgent."
  aliases:
    - "Priority/Critical 🚨"

#MARK: Status
- name: "🔁 Duplicated"
  color: "#CFD3D7" # GitHub Default Label Color
  description: "This already exists."
  aliases:
    - "duplicate" # GitHub Default Label
    - "Status/Duplicated 🔁"
- name: "⛑️ HelpWanted"
  color: "#008672" # GitHub Default Label Color
  description: "This needs extra help."
  aliases:
    - "help wanted" # GitHub Default Label
    - "Status/HelpWanted ⛑️"
- name: "⚠️ Invalid"
  color: "#E4E669" # GitHub Default Label Color
  description: "This does not seem right."
  aliases:
    - "invalid" # GitHub Default Label
    - "Status/Invalid ⚠️"
- name: "🔍 Investigating"
  color: "#03A9F4"
  description: "This is in investigating."
  aliases:
    - "Status/Investigating 🔍"
- name: "🤷 NoSolution"
  color: "#FFFFFF"
  description: "This cannot be worked on due to no possible solution."
  aliases:
    - "Status/NoSolution 🤷"
- name: "❓ Question"
  color: "#D876E3" # GitHub Default Label Color
  description: "This needs further information."
  aliases:
    - "question" # GitHub Default Label
    - "Status/Question ❓"
- name: "↗️ Transfer"
  color: "#607D8B"
  description: "This is transferred to a more relevant place."
  aliases:
    - "Status/Transfer ↗️"
- name: "🙅 WillNotFix"
  color: "#FFFFFF" # GitHub Default Label Color
  description: "This will not be worked on."
  aliases:
    - "wontfix" # GitHub Default Label
    - "Status/WillNotFix 🙅"

#MARK: Types
- name: "🐛 Bug"
  color: "#D73A4A" # GitHub Default Label Color
  description: "Something is not working as expected or intended."
  aliases:
    - "bug" # GitHub Default Label
    - "Type/Bug 🐛"
- name: "⚙️ Chore"
  color: "#C0C0C0"
  description: "Miscellaneous task."
  aliases:
    - "Type/Chore ⚙️"
- name: "📦 Dependency"
  color: "#6D4C41"
  description: "Related to dependency."
  aliases:
    - "Type/Dependency 📦"
- name: "📓 Documentation"
  color: "#0075CA" # GitHub Default Label Color
  description: "Additions or improvements to the documentation."
  aliases:
    - "documentation" # GitHub Default Label
    - "Type/Documentation 📓"
- name: "💡 Enhancement"
  color: "#A2EEEF" # GitHub Default Label Color
  description: "New feature or request."
  aliases:
    - "enhancement" # GitHub Default Label
    - "Type/Enhancement 💡"
