# ==================
# hugoalh GitHub Issues Configuration
#   Language:
#     YAML
#   Version:
#     20210303
#   Schema:
#     https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
# ==================
blank_issues_enabled: true
