# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Bug Report"
description: "Report a bug."
labels:
  - "Status/Pending 🔵"
  - "Type/Bug 🐛"
body:
  - type: "input"
    id: "version"
    attributes:
      label: "Version"
      description: |-
        Which versions occur this bug?

        > [!NOTE]
        > - Also accept common versions range syntax.
        > - For multiple values, separate each value with `, ` (comma-space).
        > - Versions must be listed as supported in the Security Policy (file `SECURITY.md`).
      placeholder: "1.2.3"
    validations:
      required: true
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: |-
        What the bug is? If needed, use images, videos, or other media to help for explain this bug.

        > [!NOTE]
        > - For external media, please ensure we are able to view those without any extra steps.
        > - Should not blur anything in these media, except for personal informations.
      placeholder: |-
        It unable to XXXXXXXX.
    validations:
      required: true
  - type: "input"
    id: "behaviour-expected"
    attributes:
      label: "Behaviour Expected"
      description: |-
        What things should expected to happen?
      placeholder: |-
        It should XXXXXXXX.
    validations:
      required: false
  - type: "input"
    id: "behaviour-actual"
    attributes:
      label: "Behaviour Actual"
      description: |-
        What things happened instead of the expected?
      placeholder: |-
        It XXXXXXXX.
    validations:
      required: false
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "To Reproduce"
      description: |-
        Is this bug reproducible? If reproducible, please show the reproduce steps; If needed, use images, videos, or other media to help for show the reproduce steps.

        > [!NOTE]
        > - For external media, please ensure we are able to view those without any extra steps.
        > - Should not blur anything in these media, except for personal informations.
      placeholder: |-
        1. Go to XXXXXXXX.
        2. Click on XXXXXXXX.
        3. Scroll to XXXXXXXX.
        4. Encounter this bug.
    validations:
      required: false
  - type: "dropdown"
    id: "frequency"
    attributes:
      label: "Frequency"
      description: |-
        How often does this bug occur?

        - **`100%`:** Always
        - **`75%`:** Frequently
        - **`50%`:** Half
        - **`25%`:** Sometimes
        - **`5%`:** Rarely
      options:
        - "100%"
        - "75%"
        - "50%"
        - "25%"
        - "5%"
      multiple: false
    validations:
      required: false
  - type: "textarea"
    id: "execution-environment"
    attributes:
      label: "Execution Environment"
      description: |-
        How is the execution environment? Different browsers, operate systems, screen sizes, or zoom levels may have differently.

        These are common properties:

        | **Property** | **Description** | **Example** |
        |:--|:--|:--|
        | Type | Device type. | Computer / Phone / Server / ... |
        | Hardware | Hardware specifications. |  |
        | Platforms | Operate system and softwares, with architecture and version. | Windows 11 23H2 X64 / NodeJS 20.6.0 X64 / Deno 1.36.0 X64 / ... |
        | Is Sub System | Whether the execution environment in the sub system? | False / True |
        | Environment Variables | Environment variables. | NO_COLOR=1 / ... |

        > [!NOTE]
        > - Accept multiple execution environments.
        > - All of the properties are optional.
        > - It is recommended to provide this information for reproducible steps.
        
        **\[🖌️ YAML\]**
      render: "yml"
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |-
        If there have information which relevant to this bug but not suitable at other fields, please list those at here.
    validations:
      required: false
