# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Documentation Issue"
description: "Report a documentation issue."
labels:
  - "documentation 📚"
body:
  - type: "textarea"
    id: "document"
    attributes:
      label: "Document"
      description: |-
        Which document path occur this issue?

        Accept multiple documents path.
      render: "yml"
      placeholder: |-
        README.md
    validations:
      required: true
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: |-
        What the issue is?
        
        If needed, use images, videos, or other types of media to help for explain this issue. Not accept any external resource.
    validations:
      required: true
  - type: "textarea"
    id: "additional"
    attributes:
      label: "Additional"
      description: |-
        Information which relevant to this issue but not suitable at other fields.
    validations:
      required: false
