content: "🎉 Happy birthday, hugoalh! 🎂"
# username:
# avatar_url:
# tts: false
# embeds:
#   - title:
#     description:
#     url:
#     color:
#     footer:
#       text:
#       icon_url:
#     image:
#       url:
#     thumbnail:
#       url:
#     video:
#       url:
#     author:
#       name:
#       url:
#       icon_url:
#     fields:
#       - name:
#         value:
#         inline: false
