# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Fix GitHub Container Tag"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: "string"
        description: "{string} Tag."
        required: true
      label:
        type: "string"
        description: "{string} Label."
        required: true
jobs:
  main:
    permissions:
      contents: "read"
      packages: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Sign In To GitHub"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{github.actor}}"
          password: "${{secrets.GITHUB_TOKEN}}"
      - shell: "pwsh"
        env:
          CDV_LABEL: "${{inputs.label}}"
          CDV_TAG: "${{inputs.tag}}"
        run: |-
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $True
          docker buildx imagetools create "ghcr.io/$($Env:GITHUB_REPOSITORY):$($Env:CDV_TAG)" --tag "ghcr.io/$($Env:GITHUB_REPOSITORY):$($Env:CDV_LABEL)"
