# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish NodeJS Package"
on:
  release:
    types:
      - "published"
jobs:
  main:
    name: "Main"
    permissions:
      contents: "write"
      id-token: "write"
    uses: "hugoalh/hugoalh/.github/workflows/call-publish-nodejs-package-0.yml@main"
    secrets:
      NPM_TOKEN: "${{secrets.NPM_TOKEN}}"
