# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish PowerShell Module"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
jobs:
  psg:
    name: "PowerShell Gallery"
    permissions:
      contents: "write"
    runs-on: "windows-latest"
    env:
      INPUT_BUILDER: ""
      INPUT_CONTEXT: ".\\"
      INPUT_TOKEN: "${{secrets.POWERSHELLGALLERY_TOKEN}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Setup PowerShell Environment"
        shell: "pwsh"
        run: |-
          $PSRepositoryPSGalleryMeta = Get-PSRepository -Name 'PSGallery'
          If ($PSRepositoryPSGalleryMeta.InstallationPolicy -ine 'Trusted') {
            Write-Host -Object 'Tweak PowerShell repository configuration.'
            Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted' -Verbose
          }
      - name: "Resolve Metadata"
        id: "metadata"
        shell: "pwsh"
        run: |-
          $ManifestsPath = Get-ChildItem -LiteralPath $Env:INPUT_CONTEXT -Filter '*.psd1' -File
          If ($ManifestsPath.Count -ne 1) {
            Write-Host -Object "::error::Missing PowerShell module manifest file!"
            Exit 1
          }
          [String]$ManifestPath = $ManifestsPath.FullName
          $ManifestFromTest = Test-ModuleManifest -Path $ManifestPath -Verbose
          $ManifestFromData = Import-PowerShellDataFile -LiteralPath $ManifestPath -SkipLimitCheck
          [String]$Name = $ManifestFromTest.Name
          [String]$Version = $ManifestFromData.ModuleVersion
          If ($Null -ine $ManifestFromData.PrivateData.PSData.Prerelease) {
            $Version += "-$($ManifestFromData.PrivateData.PSData.Prerelease)"
          }
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "ballname=$($Name.ToLower()).$($Version).nupkg" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Build Package"
        if: "${{inputs.builder != ''}}"
        shell: "pwsh"
        run: |-
          . ".\$($Env:INPUT_BUILDER)"
      - name: "Publish Package To PowerShell Gallery"
        shell: "pwsh"
        run: |-
          Publish-Module -Path $Env:INPUT_CONTEXT -NugetAPIKey $Env:INPUT_TOKEN -Force -Verbose
    outputs:
      package-ballname: "${{steps.metadata.outputs.ballname}}"
  release-assets:
    name: "Release Assets"
    needs:
      - "psg"
    if: "${{needs.psg.result == 'success'}}"
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Wait For PowerShell Gallery Data Update"
        shell: "pwsh"
        run: |-
          Start-Sleep -Seconds 300
      - name: "Upload Package `${{needs.psg.outputs.package-ballname}}` To GitHub Release Tag `${{github.event.release.tag_name}}`"
        env:
          GH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        shell: "pwsh"
        run: |-
          [String]$BallName = '${{needs.psg.outputs.package-ballname}}'
          Invoke-WebRequest -Uri "https://psg-prod-eastus.azureedge.net/packages/$($BallName)" -MaximumRedirection 1 -MaximumRetryCount 5 -RetryIntervalSec 5 -Method 'GET' -OutFile $BallName
          gh release upload '${{github.event.release.tag_name}}' $BallName --clobber --repo $Env:GITHUB_REPOSITORY
