# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish Deno Package"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
    inputs:
      commit:
        type: "string"
        description: "Target commit SHA."
      jsr:
        type: "choice"
        description: "Whether publish package to JSR."
        options:
          - "auto"
          - "false"
        default: "auto"
      npm:
        type: "choice"
        description: "Whether publish package to NPM."
        options:
          - "auto"
          - "false"
        default: "auto"
jobs:
  main:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"
        with:
          ref: "${{inputs.commit || github.ref}}"
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v2"
        with:
          deno-version: "^2.4.5"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v4"
        with:
          node-version: "lts/*"
          check-latest: true
      - name: "Get Cache Path"
        shell: "pwsh"
        run: |-
          [PSCustomObject]$DenoInfo = ConvertFrom-Json -InputObject (
            deno info --json |
              Join-String -Separator "`n"
          ) -Depth 100
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_DENO_CACHE_PATH_ROOT=$($DenoInfo.denoDir)" -Confirm:$False -Encoding 'UTF8NoBOM'
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_DENO_CACHE_PATH_FLUSHES=$(ConvertTo-Json -InputObject @(
            $DenoInfo.typescriptCache
          ) -Depth 100 -Compress)" -Confirm:$False -Encoding 'UTF8NoBOM'
          [String]$NpmCachePath = (
            npm config get cache |
              Join-String -Separator "`n"
          ).Trim()
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_CACHE_PATH_ROOT=$($NpmCachePath)" -Confirm:$False -Encoding 'UTF8NoBOM'
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_CACHE_PATH_FLUSHES=$(ConvertTo-Json -InputObject @(
            (Join-Path -Path $NpmCachePath -ChildPath '_logs')
          ) -Depth 100 -Compress)" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Load Deno Cache"
        uses: "actions/cache/restore@v4"
        with:
          key: "${{runner.os}}/Deno/${{github.run_id}}/${{github.run_attempt}}/${{github.job}}"
          restore-keys: |-
            ${{runner.os}}/Deno/${{github.run_id}}/${{github.run_attempt}}/
            ${{runner.os}}/Deno/${{github.run_id}}/
            ${{runner.os}}/Deno/
          path: "${{env.CDV_DENO_CACHE_PATH_ROOT}}"
      - name: "Load NPM Cache"
        uses: "actions/cache/restore@v4"
        with:
          key: "${{runner.os}}/NPM/${{github.run_id}}/${{github.run_attempt}}/${{github.job}}"
          restore-keys: |-
            ${{runner.os}}/NPM/${{github.run_id}}/${{github.run_attempt}}/
            ${{runner.os}}/NPM/${{github.run_id}}/
            ${{runner.os}}/NPM/
          path: "${{env.CDV_NPM_CACHE_PATH_ROOT}}"
      - name: "Setup NPM"
        run: |-
          npm --global config set git-tag-version false
      - name: "Resolve Metadata"
        shell: "pwsh"
        env:
          CDV_JSR_PUBLISH_DISPATCH: "${{inputs.jsr || 'auto'}}"
          CDV_NPM_PUBLISH_DISPATCH: "${{inputs.npm || 'auto'}}"
        run: |-
          [PSCustomObject]$Config = ConvertFrom-Json -InputObject (Get-Content -LiteralPath '.\deno.jsonc' -Raw -Encoding 'UTF8NoBOM') -Depth 100
          [Boolean]$Build = $Null -ine $Config.tasks.build
          [Boolean]$JSRPublish = $Env:CDV_JSR_PUBLISH_DISPATCH -ieq 'auto' -and $Null -ine $Config.tasks.'jsr-publish'
          [Boolean]$NPMBuild = $Null -ine $Config.tasks.'npm-build'
          [Boolean]$NPMDistributionRelative = $Null -ine $Config.tasks.'npm-var-distribution-relative'
          [Boolean]$NPMPublish = $Env:CDV_NPM_PUBLISH_DISPATCH -ieq 'auto' $Null -ine $Config.tasks.'npm-publish'
          Add-Content -LiteralPath $Env:GITHUB_STEP_SUMMARY -Value @"
          # Dispatch

          - **Build:** $($Build ? '✔️' : '❌')
          - **JSR:**
            - **Publish:** $($JSRPublish ? '✔️' : '❌')
          - **NPM:**
            - **Build:** $($NPMBuild ? '✔️' : '❌')
            - **DistributionRelative:** $($NPMDistributionRelative ? '✔️' : '❌')
            - **Publish:** $($NPMPublish ? '✔️' : '❌')
          "@
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_BUILD=$(($Null -ine $Config.tasks.build).ToString().ToLower())"
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_JSR_PUBLISH=$($JSRPublish.ToString().ToLower())"
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_BUILD=$($NPMBuild.ToString().ToLower())"
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_DISTRIBUTION_RELATIVE=$((
            deno task npm-var-distribution-relative |
              Join-String -Separator "`n"
          ).Trim())"
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_PUBLISH=$($NPMPublish.ToString().ToLower())"
      - name: "Build Repository"
        id: "build-general"
        if: "${{env.CDV_BUILD == 'true'}}"
        run: |-
          deno task build
      - name: "Publish Package To JSR"
        if: "${{!cancelled() && (steps.build-general.outcome == 'success' || steps.build-general.outcome == 'skip') && env.CDV_JSR_PUBLISH == 'true'}}"
        run: |-
          deno task jsr-publish
      - name: "Build Package For NPM"
        id: "build-npm"
        if: "${{!cancelled() && (steps.build-general.outcome == 'success' || steps.build-general.outcome == 'skip') && env.CDV_NPM_PUBLISH == 'true' && env.CDV_NPM_BUILD == 'true'}}"
        run: |-
          deno task npm-build
      - name: "Publish Package To NPM (Pre)"
        id: "publish-npm-pre"
        if: "${{!cancelled() && (steps.build-npm.outcome == 'success' || steps.build-npm.outcome == 'skip') && env.CDV_NPM_PUBLISH == 'true'}}"
        shell: "pwsh"
        env:
          CDV_NPM_TOKEN: "${{secrets.NPM_TOKEN}}"
        run: |-
          npm --global config set //registry.npmjs.org/:_authToken $Env:CDV_NPM_TOKEN
          npm --global config set provenance true
          [PSCustomObject]$Manifest = ConvertFrom-Json -InputObject (Get-Content -LiteralPath (Join-Path -Path $Env:CDV_NPM_DISTRIBUTION_RELATIVE -ChildPath 'package.json') -Raw -Encoding 'UTF8NoBOM') -Depth 100
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_PACKAGE_NAME=$($Manifest.Name)" -Confirm:$False -Encoding 'UTF8NoBOM'
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "CDV_NPM_PACKAGE_VERSION=$($Manifest.version)" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Publish Package To NPM"
        if: "${{!cancelled() && steps.publish-npm-pre.outcome == 'success'}}"
        run: |-
          deno task npm-publish
      - name: "Publish Package To NPM (Post)"
        if: "${{!cancelled() && steps.publish-npm-pre.outcome == 'success'}}"
        run: |-
          Try {
            [String[]]$Versions = ConvertFrom-Json -InputObject (
              npm view $Env:CDV_NPM_PACKAGE_NAME versions --json |
                Join-String -Separator "`n"
            ) -Depth 100
            [SemVer]$VersionCurrent = [SemVer]::Parse($Env:CDV_NPM_PACKAGE_VERSION)
            [SemVer]$VersionLatest = $Versions |
              ForEach-Object -Process {
                [SemVer]::Parse($_)
              } |
              Sort-Object |
              Select-Object -Last 1
            If ($VersionCurrent -ge $VersionLatest) {
              npm dist-tag add "$($Env:CDV_NPM_PACKAGE_NAME)@$($Env:CDV_NPM_PACKAGE_VERSION)" latest
            }
          }
          Catch { }
          npm dist-tag rm $Env:CDV_NPM_PACKAGE_NAME publish
          npm --global config delete provenance
          npm --global config delete //registry.npmjs.org/:_authToken
      - name: "Flush Cache"
        if: "${{!cancelled()}}"
        shell: "pwsh"
        run: |-
          ConvertFrom-Json -InputObject ($Env:CDV_DENO_CACHE_PATH_FLUSHES ?? '[]') -Depth 100 |
            ForEach-Object -Process {
              Remove-Item -LiteralPath $_ -Recurse -Confirm:$False -ErrorAction 'SilentlyContinue'
            }
          ConvertFrom-Json -InputObject ($Env:CDV_NPM_CACHE_PATH_FLUSHES ?? '[]') -Depth 100 |
            ForEach-Object -Process {
              Remove-Item -LiteralPath $_ -Recurse -Confirm:$False -ErrorAction 'SilentlyContinue'
            }
      - name: "Save Deno Cache"
        if: "${{!cancelled()}}"
        uses: "actions/cache/save@v4"
        with:
          key: "${{runner.os}}/Deno/${{github.run_id}}/${{github.run_attempt}}/${{github.job}}"
          path: "${{env.CDV_DENO_CACHE_PATH_ROOT}}"
      - name: "Save NPM Cache"
        if: "${{!cancelled()}}"
        uses: "actions/cache/save@v4"
        with:
          key: "${{runner.os}}/NPM/${{github.run_id}}/${{github.run_attempt}}/${{github.job}}"
          path: "${{env.CDV_NPM_CACHE_PATH_ROOT}}"
