# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Review NodeJS Code"
on:
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  push:
    branches:
      - "**"
  workflow_dispatch:
env:
  CDV_RUN_SKIP: "${{github.event_name == 'pull_request' && github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id}}"
jobs:
  main:
    name: "${{matrix.run_on}}"
    if: "${{env.CDV_RUN_SKIP == 'false'}}"
    permissions:
      contents: "read"
    strategy:
      matrix:
        run_on:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false
    runs-on: "${{matrix.run_on}}"
    env:
      CDV_RUN_LITE: "${{matrix.run_on != 'ubuntu-latest'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v4"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Get NPM Cache Path"
        id: "npm-cache-path"
        shell: "pwsh"
        run: |-
          [String]$NpmCachePath = (
            npm config get cache |
              Join-String -Separator "`n"
          ).Trim()
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "value=$($NpmCachePath)" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Restore NPM Cache"
        id: "npm-cache-restore"
        uses: "actions/cache/restore@v4"
        with:
          key: "${{runner.os}}/NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          restore-keys: |-
            ${{runner.os}}/NPM/${{github.run_id}}-${{github.run_attempt}}-
            ${{runner.os}}/NPM/${{github.run_id}}-
            ${{runner.os}}/NPM/
          path: "${{steps.npm-cache-path.outputs.value}}"
      - name: "Analyze Repository"
        id: "analyze"
        shell: "pwsh"
        run: |-
          [PSCustomObject]$Config = Get-Content -LiteralPath '.\package.json' -Encoding 'UTF8NoBOM' |
            ConvertFrom-Json -Depth 100
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "build=$(($Null -ine $Config.scripts.build).ToString().ToLower())"
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "test=$(($Null -ine $Config.scripts.test).ToString().ToLower())"
      - name: "Check Repository"
        if: "${{!cancelled() && steps.analyze.outcome == 'success' && env.CDV_RUN_LITE == 'false'}}"
        shell: "pwsh"
        run: |-
          [String[]]$FilesForbid = Get-ChildItem -LiteralPath '.\' -Include @('*.js', '*.jsx', '*.mjs', '*.mts') -File -Recurse -Name
          If ($FilesForbid.Count -gt 0) {
            Write-Error -Message "Repository contains forbid file formats (``.js``, ``.jsx``, ``.mjs``, ``.mts``): $(
              $FilesForbid |
                Join-String -Separator ', '
            )" -ErrorAction 'Stop'
          }
      - name: "Install Dependencies"
        if: "${{!cancelled() && steps.analyze.outcome == 'success'}}"
        run: |-
          npm install
      - name: "Build Repository"
        if: "${{!cancelled() && steps.analyze.outcome == 'success' && steps.analyze.outputs.build == 'true'}}"
        run: |-
          npm run build
      - name: "Test Code"
        if: "${{!cancelled() && steps.analyze.outcome == 'success' && steps.analyze.outputs.test == 'true'}}"
        run: |-
          npm run test
      - name: "Check Deployment"
        if: "${{!cancelled() && steps.analyze.outcome == 'success' && env.CDV_RUN_LITE == 'false'}}"
        run: |-
          npm publish --dry-run
      - name: "Save NPM Cache"
        if: "${{!cancelled() && steps.npm-cache-restore.outcome == 'success'}}"
        uses: "actions/cache/save@v4"
        with:
          key: "${{runner.os}}/NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          path: "${{steps.npm-cache-path.outputs.value}}"
  skip:
    if: "${{env.CDV_RUN_SKIP == 'true'}}"
    permissions: {}
    runs-on: "ubuntu-latest"
    steps:
      - run: |-
          sleep 1
