# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Review ES Code"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
jobs:
  analyze:
    name: "Analyze"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Analyze Repository"
        id: "analyze"
        shell: "pwsh"
        run: |-
          [Boolean]$DenoBase = Test-Path -LiteralPath '.\deno.jsonc' -PathType 'Leaf'
          [Boolean]$NodeJSBase = Test-Path -LiteralPath '.\package.json' -PathType 'Leaf'
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "deno-base=$($DenoBase.ToString().ToLower())"
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "nodejs-base=$($NodeJSBase.ToString().ToLower())"
          If ($DenoBase) {
            [PSCustomObject]$DenoConfig = Get-Content -LiteralPath '.\deno.jsonc' -Encoding 'UTF8NoBOM' |
              ConvertFrom-Json -Depth 100
            [String[]]$DenoFilesBenchmark = Get-ChildItem -LiteralPath '.\' -Include @('*.bench.ts', '*.bench.tsx', '*_bench.ts', '*_bench.tsx', 'bench.ts', 'bench.tsx') -File -Recurse -Name
            [String[]]$DenoFilesTest = Get-ChildItem -LiteralPath '.\' -Include @('*.test.ts', '*.test.tsx', '*_test.ts', '*_test.tsx', 'test.ts', 'test.tsx') -File -Recurse -Name
            Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "deno-benchmark=$(($DenoFilesBenchmark.Count -gt 0).ToString().ToLower())"
            Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "deno-test=$(($DenoFilesTest.Count -gt 0).ToString().ToLower())"
            Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "deno-jsr-check=$(($Null -ine $DenoConfig.tasks.('jsr-check')).ToString().ToLower())"
            Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "deno-npm-build=$(($Null -ine $DenoConfig.tasks.('npm-build')).ToString().ToLower())"
          }
    outputs:
      deno-base: "${{steps.analyze.outputs.deno-base}}"
      deno-benchmark: "${{steps.analyze.outputs.deno-benchmark}}"
      deno-jsr-check: "${{steps.analyze.outputs.deno-jsr-check}}"
      deno-npm-build: "${{steps.analyze.outputs.deno-npm-build}}"
      deno-test: "${{steps.analyze.outputs.deno-test}}"
      nodejs-base: "${{steps.analyze.outputs.nodejs-base}}"
  check:
    name: "Check"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Check Repository"
        shell: "pwsh"
        run: |-
          [String[]]$FilesForbid = Get-ChildItem -LiteralPath '.\' -Include @('*.js', '*.jsx', '*.mjs', '*.mts') -File -Recurse -Name
          If ($FilesForbid.Count -gt 0) {
            Write-Error -Message "Repository contains forbid file formats (``.js``, ``.jsx``, ``.mjs``, ``.mts``): $(
              $FilesForbid |
                Join-String -Separator ', '
            )" -ErrorAction 'Stop'
          }
  deno:
    name: "Deno - ${{matrix.runon}}"
    permissions:
      contents: "read"
    needs:
      - "analyze"
    if: "${{needs.analyze.result == 'success' && needs.analyze.outputs.deno-base == 'true'}}"
    strategy:
      matrix:
        runon:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false
    runs-on: "${{matrix.runon}}"
    env:
      CDV_RUN_LITE: "${{matrix.runon != 'ubuntu-latest'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1.4.1"
        with:
          deno-version: "^1.46.3"
      - name: "Get Deno Cache Path"
        id: "deno-cache-path"
        shell: "pwsh"
        run: |-
          [PSCustomObject]$DenoInfo = deno info --json |
            ConvertFrom-Json -Depth 100
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "value=$($DenoInfo.denoDir)" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Restore Deno Cache"
        id: "deno-cache-restore"
        uses: "actions/cache/restore@v4.0.2"
        with:
          key: "Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          restore-keys: |-
            Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-
            Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}
            Deno/${{runner.os}}-${{github.run_id}}-
            Deno/${{runner.os}}-${{github.run_id}}
            Deno/${{runner.os}}-
            Deno/${{runner.os}}
            Deno/
          path: "${{steps.deno-cache-path.outputs.value}}"
      - name: "Verify Code"
        shell: "pwsh"
        run: |-
          [String[]]$Files = Get-ChildItem -LiteralPath '.\' -Include @('*.ts', '*.tsx') -File -Recurse -Name
          [Boolean]$ShouldReload = $Env:GITHUB_EVENT_NAME -iin @('schedule')
          ForEach ($File In $Files) {
            $ShouldReload ? (deno cache --reload $File) : (deno cache $File)
          }
      - name: "Lint Code"
        if: "${{!cancelled()}}"
        run: |-
          deno lint
      - name: "Test Code"
        id: "deno-test"
        if: "${{!cancelled() && needs.analyze.outputs.deno-test == 'true'}}"
        run: |-
          deno test --allow-all --coverage --no-prompt
      - name: "List Test Code Coverage"
        if: "${{!cancelled() && needs.analyze.outputs.deno-test == 'true' && (steps.deno-test.outcome == 'failure' || steps.deno-test.outcome == 'success')}}"
        run: |-
          deno coverage
      - name: "Benchmark Code"
        if: "${{!cancelled() && needs.analyze.outputs.deno-benchmark == 'true'}}"
        run: |-
          deno bench --allow-all --no-prompt
      # - name: "Check Dependencies Update"
      #   if: "${{!cancelled() && env.CDV_RUN_LITE == 'false' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')}}"
      #   shell: "pwsh"
      #   run: |-
      #     [String]$Output = deno run --allow-net "--allow-read=$($Env:GITHUB_WORKSPACE)" --no-prompt https://deno.land/x/udd@0.8.2/main.ts --dry-run **/*.ts **/*.tsx deno.jsonc *>&1 |
      #       Join-String -Separator "`n"
      #     $LASTEXITCODE = 0
      #     Write-Host -Object $Output
      #     If ($Output -imatch 'able to update') {
      #       Write-Warning -Message 'Found dependencies that need to update!'
      #     }
      - name: "Check Deployment For JSR"
        if: "${{!cancelled() && env.CDV_RUN_LITE == 'false' && needs.analyze.outputs.deno-jsr-check == 'true'}}"
        run: |-
          deno task jsr-check
      - name: "Check Deployment For NPM"
        if: "${{!cancelled() && env.CDV_RUN_LITE == 'false' && needs.analyze.outputs.deno-npm-build == 'true'}}"
        run: |-
          deno task npm-build
      - name: "Save Deno Cache"
        if: "${{!cancelled() && steps.deno-cache-restore.outcome == 'success'}}"
        uses: "actions/cache/save@v4.0.2"
        with:
          key: "Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          path: "${{steps.deno-cache-path.outputs.value}}"
  nodejs:
    name: "NodeJS - ${{matrix.runon}}"
    permissions:
      contents: "read"
    needs:
      - "analyze"
    if: "${{needs.analyze.result == 'success' && needs.analyze.outputs.nodejs-base == 'true'}}"
    strategy:
      matrix:
        runon:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false
    runs-on: "${{matrix.runon}}"
    env:
      CDV_RUN_LITE: "${{matrix.runon != 'ubuntu-latest'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v4.0.3"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Get NPM Cache Path"
        id: "npm-cache-path"
        shell: "pwsh"
        run: |-
          [String]$NpmCachePath = (
            npm config get cache |
              Join-String -Separator "`n"
          ).Trim()
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "value=$($NpmCachePath)" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Restore NPM Cache"
        id: "npm-cache-restore"
        uses: "actions/cache/restore@v4.0.2"
        with:
          key: "NPM/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          restore-keys: |-
            NPM/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-
            NPM/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}
            NPM/${{runner.os}}-${{github.run_id}}-
            NPM/${{runner.os}}-${{github.run_id}}
            NPM/${{runner.os}}-
            NPM/${{runner.os}}
            NPM/
          path: "${{steps.npm-cache-path.outputs.value}}"
      - name: "Save NPM Cache"
        if: "${{!cancelled() && steps.npm-cache-restore.outcome == 'success'}}"
        uses: "actions/cache/save@v4.0.2"
        with:
          key: "NPM/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          path: "${{steps.npm-cache-path.outputs.value}}"
