# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "bun"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency 📦"
      - "bun"
    pull-request-branch-name:
      separator: "/"
    cooldown:
      default-days: 1
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency 📦"
      - "rust"
    pull-request-branch-name:
      separator: "/"
    cooldown:
      default-days: 1
  - package-ecosystem: "deno"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency 📦"
      - "deno"
    pull-request-branch-name:
      separator: "/"
    cooldown:
      default-days: 1
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency 📦"
      - "docker"
    pull-request-branch-name:
      separator: "/"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency 📦"
      - "github-actions"
    pull-request-branch-name:
      separator: "/"
    cooldown:
      default-days: 1
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency 📦"
      - "nodejs"
    pull-request-branch-name:
      separator: "/"
    versioning-strategy: "increase-if-necessary"
    cooldown:
      default-days: 1
