name: "Announce New Release - Discord (Reusable Workflow)"
on:
  workflow_call:
    inputs:
      name:
        type: "string"
        description: "{string} Repository name."
        required: true
      color:
        type: "string"
        description: "{string} Color."
        required: false
        default: "random"
      thumbnail:
        type: "string"
        description: "{string} Thumbnail."
        required: false
      repositories:
        type: "string"
        description: "{string} Repositories."
        required: false
        default: |
          **- GitHub (${{github.event.repository.full_name}}):** ${{github.event.repository.html_url}}
      releases:
        type: "string"
        description: "{string} Releases."
        required: false
        default: |
          **- GitHub (& Changelog):** ${{github.event.release.html_url}}
    secrets:
      DISCORD_WEBHOOK:
        description: "{string} Discord webhook."
        required: true
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.3.0"
        with:
          toolkit_version: "1.6.0-beta4"
          toolkit_allowprerelease: "True"
      - name: "Resolve YAML"
        id: "resolve-yaml"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$Repositories = @'
          ${{inputs.repositories}}
          '@
          [String]$Releases = @'
          ${{inputs.releases}}
          '@
          Set-GitHubActionsOutput -Name 'repositories' -Value ($Repositories -ireplace '\r?\n', '\n')
          Set-GitHubActionsOutput -Name 'releases' -Value ($Releases -ireplace '\r?\n', '\n')
        shell: "pwsh"
      - name: "Send Discord Webhook"
        uses: "hugoalh/send-discord-webhook-ghaction@v5.0.6"
        with:
          key: "${{secrets.DISCORD_WEBHOOK}}"
          payload: |
            embeds:
              - title: "${{inputs.name}}"
                description: |
                  > ${{github.event.repository.description}}

                  Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) just released!
                timestamp: "${{github.event.release.published_at}}"
                color: "${{inputs.color}}"
                thumbnail:
                  url: "${{inputs.thumbnail}}"
                author:
                  name: "${{github.event.release.author.login}}"
                  url: "${{github.event.release.author.html_url}}"
                  icon_url: "${{github.event.release.author.avatar_url}}"
                fields:
                  - name: "Repositories"
                    value: "${{steps.resolve-yaml.outputs.repositories}}"
                    inline: false
                  - name: "Releases"
                    value: "${{steps.resolve-yaml.outputs.releases}}"
                    inline: false
          wait: "true"
