# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Scan Virus (@0)"
on:
  workflow_call:
    inputs:
      git_integrate:
        type: "string"
        description: "{Boolean} Whether to integrate with Git to perform scan by every commits."
        required: false
        default: "False"
      git_ignores:
        type: "string"
        description: "{ScriptBlock} Ignores by the Git commits."
        required: false
      git_limit:
        type: "string"
        description: "{UInt64} Limit on how many Git commits will scan."
        required: false
        default: "0"
      git_reverse:
        type: "string"
        description: "{Boolean} Whether to reverse the scan order of the Git commits."
        required: false
        default: "False"
      ignores_pre:
        type: "string"
        description: "{ScriptBlock} Ignores by the paths, sessions, and tools before the scan."
        required: false
      ignores_post:
        type: "string"
        description: "{ScriptBlock} Ignores by the paths, sessions, symbols (i.e. rules or signatures), and tools after the scan."
        required: false
jobs:
  main:
    name: "Main"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.2"
        with:
          fetch-depth: "0"
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/clamav@v0.20.1"
        with:
          git_integrate: "${{inputs.git_integrate}}"
          git_ignores: "${{inputs.git_ignores}}"
          git_limit: "${{inputs.git_limit}}"
          git_reverse: "${{inputs.git_reverse}}"
          ignores_pre: "${{inputs.ignores_pre}}"
          ignores_post: "${{inputs.ignores_post}}"
