# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Invoke DevSkim Analysis (@0)"
on:
  workflow_call:
jobs:
  main:
    name: "Main"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
        with:
          fetch-depth: "0"
      - name: "Analyze Repository"
        uses: "microsoft/DevSkim-Action@v1.0.14"
      - name: "Upload Analysis Result"
        uses: "github/codeql-action/upload-sarif@v3.26.2"
        with:
          sarif_file: "devskim-results.sarif"
