# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Map SemVer Soft Tag (@1)"
on:
  workflow_call:
    inputs:
      patterns_latest:
        type: "string"
        description: "{String[]} Patterns for the latest release."
        required: false
      patterns_pre:
        type: "string"
        description: "{String[]} Patterns for the pre release."
        required: false
    secrets:
      token:
        description: "{String} GitHub personal access token."
        required: true
jobs:
  main:
    name: "Main"
    permissions: {}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.6"
        with:
          token: "${{secrets.token}}"
          fetch-depth: "0"
      - name: "Config Git"
        shell: "pwsh"
        run: |
          git --no-pager config --global 'user.name' 'github-actions'
          git --no-pager config --global 'user.email' 'github-actions@users.noreply.github.com'
      - name: "Update Soft Tag"
        env:
          INPUT_PATTERNS_LATEST: "${{inputs.patterns_latest}}"
          INPUT_PATTERNS_PRE: "${{inputs.patterns_pre}}"
        shell: "pwsh"
        run: |
          [String[]]$SemVerParts = @('Major', 'Minor', 'Patch', 'PreReleaseLabel', 'BuildLabel')
          [String[]]$SoftTagPatternsLatest = $Env:INPUT_PATTERNS_LATEST -isplit '\r?\n' |
            ForEach-Object -Process { $_.Trim() } |
            Where-Object -FilterScript { $_.Length -gt 0 }
          [String[]]$SoftTagPatternsPre = $Env:INPUT_PATTERNS_PRE -isplit '\r?\n' |
            ForEach-Object -Process { $_.Trim() } |
            Where-Object -FilterScript { $_.Length -gt 0 }
          [SemVer[]]$Tags = git --no-pager tag --list |
            Where-Object -FilterScript { $_ -imatch '^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-.+?)?(?:\+.+?)?$' } |
            ForEach-Object -Process {
              Try {
                [SemVer]::Parse(($_ -ireplace '^v', ''))
              }
              Catch {
              }
            } |
            Sort-Object
          Write-Debug -Message "Tags [$($Tags.Count)]: $(
            $Tags |
              ForEach-Object -Process { $_.ToString() } |
              Join-String -Separator ', '
          )" -Debug
          [Hashtable]$SoftTags = @{}
          ForEach ($Tag In $Tags) {
            If ($Null -eq $Tag.PreReleaseLabel -and $Null -eq $Tag.BuildLabel) {
              ForEach ($SoftTagPatternLatest In $SoftTagPatternsLatest) {
                [String]$SoftTagLatest = $SoftTagPatternLatest
                ForEach ($SemVerPart In $SemVerParts) {
                  If ($Null -ne $Tag.($SemVerPart)) {
                    $SoftTagLatest = $SoftTagLatest -ireplace "\{\{$($SemVerPart)\}\}", $Tag.($SemVerPart).ToString()
                  }
                }
                $SoftTags.($SoftTagLatest) = $Tag
              }
            }
            ForEach ($SoftTagPatternPre In $SoftTagPatternsPre) {
              [String]$SoftTagPre = $SoftTagPatternPre
              ForEach ($SemVerPart In $SemVerParts) {
                If ($Null -ne $Tag.($SemVerPart)) {
                  $SoftTagPre = $SoftTagPre -ireplace "\{\{$($SemVerPart)\}\}", $Tag.($SemVerPart).ToString()
                }
              }
              $SoftTags.($SoftTagPre) = $Tag
            }
          }
          Write-Debug -Message "Soft Tags [$($SoftTags.Count)]: $(
            $SoftTags.GetEnumerator() |
              ForEach-Object -Process { "$($_.Name): $($_.Value.ToString())" } |
              Join-String -Separator ', '
          )" -Debug
          ForEach ($SoftTag In $SoftTags.GetEnumerator()) {
            git --no-pager tag $SoftTag.Name "v$($SoftTag.Value.ToString())" --force
            git --no-pager push origin tag $SoftTag.Name --force
          }
