# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Review Deno Code (@1)"
on:
  workflow_call:
    inputs:
      runon:
        type: "string"
        description: "{string} Type of the runner to run on."
        required: false
        default: "ubuntu-latest"
      issub:
        type: "boolean"
        description: "{boolean} Whether this is a sub (e.g.: test on specific operate system)."
        required: false
        default: false
jobs:
  main:
    name: "Main"
    permissions:
      contents: "read"
    runs-on: "${{inputs.runon}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.2"
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0"
        with:
          version: "^2.1.0"
      - name: "Resolve Metadata"
        id: "metadata"
        shell: "pwsh"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          If (!(Test-Path -LiteralPath '.\deno.jsonc' -PathType 'Leaf')) {
            Write-GitHubActionsFail -Message 'Missing Deno config file!'
          }
          [String[]]$Files = Get-ChildItem -Recurse -File -Name |
            Where-Object -FilterScript { $_ -imatch '\.(?:m?[jt]s|[jt]sx?)$' }
          [Boolean]$DispatchBenchmark = (
            $Files |
              Where-Object -FilterScript { $_ -imatch '(?:^|\/|\\|\.|_)bench\.(?:m?[jt]s|[jt]sx?)' }
          ).Count -gt 0
          [Boolean]$DispatchTest = (
            $Files |
              Where-Object -FilterScript { $_ -imatch '(?:^|\/|\\|\.|_)test\.(?:m?[jt]s|[jt]sx?)' }
          ).Count -gt 0
          Set-GitHubActionsOutput -Name 'dispatch_benchmark' -Value $DispatchBenchmark.ToString().ToLower()
          Set-GitHubActionsOutput -Name 'dispatch_jsr' -Value (Test-Path -LiteralPath '.\jsr.jsonc' -PathType 'Leaf').ToString().ToLower()
          Set-GitHubActionsOutput -Name 'dispatch_test' -Value $DispatchTest.ToString().ToLower()
          Set-GitHubActionsOutput -Name 'files' -Value (ConvertTo-Json -InputObject $Files -Depth 100 -Compress)
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1.1.4"
        with:
          deno-version: "^1.41.2"
      - name: "Resolve Cache Path"
        shell: "pwsh"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [PSCustomObject]$DenoInfo = deno info --json |
            Join-String -Separator "`n" |
            ConvertFrom-Json -Depth 100
          Set-GitHubActionsEnvironmentVariable -Name 'DENO_DIR' -Value $DenoInfo.denoDir -Scope 'Subsequent'
      - name: "Restore Deno Cache"
        id: "restore-deno-cache"
        uses: "actions/cache/restore@v4.0.1"
        with:
          key: "Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          path: "${{env.DENO_DIR}}"
          restore-keys: |-
            Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-
            Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}
            Deno/${{runner.os}}-${{github.run_id}}-
            Deno/${{runner.os}}-${{github.run_id}}
            Deno/${{runner.os}}-
            Deno/${{runner.os}}
            Deno/
      - name: "Verify Code"
        id: "verify-code"
        env:
          INPUT_FILES: "${{steps.metadata.outputs.files}}"
        shell: "pwsh"
        run: |
          [Boolean]$ShouldReload = $Env:GITHUB_EVENT_NAME -iin @('schedule')
          [Boolean]$IsFail = $False
          ForEach ($File In (
            $Env:INPUT_FILES |
              ConvertFrom-Json -Depth 100
          )) {
            Try {
              $ShouldReload ? (deno cache --reload $File) : (deno cache $File)
            }
            Catch {
              $IsFail = $True
            }
            $LASTEXITCODE = 0
          }
          If ($IsFail) {
            Exit 1
          }
      - name: "Verify JSR Metadata"
        if: "${{!cancelled() && !inputs.issub && steps.metadata.outputs.dispatch_jsr == 'true'}}"
        shell: "pwsh"
        run: |
          deno publish --config jsr.jsonc --dry-run --no-provenance --token 'ThisIsATokenPlaceholder'
      - name: "Lint Code"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success'}}"
        run: |
          deno lint
      - name: "Test Code"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success' && steps.metadata.outputs.dispatch_test == 'true'}}"
        run: |
          deno test --allow-all --coverage --no-prompt
      - name: "List Test Code Coverage"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success' && steps.metadata.outputs.dispatch_test == 'true'}}"
        run: |
          deno coverage
      - name: "Benchmark Code"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success' && steps.metadata.outputs.dispatch_benchmark == 'true'}}"
        run: |
          deno bench --allow-all --no-prompt
      - name: "Check Dependencies Update"
        if: "${{!cancelled() && !inputs.issub && steps.verify-code.outcome == 'success' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')}}"
        env:
          INPUT_FILES: "${{steps.metadata.outputs.files}}"
        shell: "pwsh"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [Boolean]$IsFail = $False
          ForEach ($File In (
            $Env:INPUT_FILES |
              ConvertFrom-Json -Depth 100
          )) {
            [String]$Output =  deno run --allow-net "--allow-read=$($Env:GITHUB_WORKSPACE)" --no-prompt https://deno.land/x/udd@0.8.2/main.ts --dry-run $File |
              Join-String -Separator "`n"
            $LASTEXITCODE = 0
            Write-Host -Object $Output
            If ($Output -imatch 'able to update') {
              $IsFail = $True
              Write-GitHubActionsError -Message "Dependencies in file ``$File`` are not up to date!"
            }
          }
          If ($IsFail) {
            Exit 1
          }
      - name: "Save Deno Cache"
        if: "${{!cancelled() && steps.restore-deno-cache.outcome == 'success'}}"
        uses: "actions/cache/save@v4.0.1"
        with:
          key: "Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          path: "${{env.DENO_DIR}}"
