# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Review Deno Code (@1)"
on:
  workflow_call:
    inputs:
      runon:
        type: "string"
        description: "{string} Type of the runner to run on."
        required: false
        default: "ubuntu-latest"
      issub:
        type: "boolean"
        description: "{boolean} Whether this is a sub review (e.g.: test on specific operate system)."
        required: false
        default: false
      jsr_hasdeployment:
        type: "boolean"
        description: "{boolean} Whether this has deployment for JSR (JavaScript Registry)."
        required: false
        default: false
      npm_hasdeployment:
        type: "boolean"
        description: "{boolean} Whether this has deployment for NPM."
        required: false
        default: false
jobs:
  main:
    name: "Main"
    permissions:
      contents: "read"
    runs-on: "${{inputs.runon}}"
    env:
      DENO_FUTURE: "1"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.2"
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1.1.4"
        with:
          deno-version: "^1.42.1"
      - name: "Get Deno Cache Path"
        shell: "pwsh"
        run: |
          [PSCustomObject]$DenoInfo = deno info --json |
            Join-String -Separator "`n" |
            ConvertFrom-Json -Depth 100
          Add-Content -LiteralPath $Env:GITHUB_ENV -Value "DENO_DIR=$($DenoInfo.denoDir)" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Restore Deno Cache"
        id: "restore-deno-cache"
        uses: "actions/cache/restore@v4.0.2"
        with:
          key: "Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          restore-keys: |-
            Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-
            Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}
            Deno/${{runner.os}}-${{github.run_id}}-
            Deno/${{runner.os}}-${{github.run_id}}
            Deno/${{runner.os}}-
            Deno/${{runner.os}}
            Deno/
          path: "${{env.DENO_DIR}}"
      - name: "Analyze Repository"
        id: "analyze-repository"
        env:
          INPUT_JSR_HASDEPLOYMENT: "${{inputs.jsr_hasdeployment}}"
          INPUT_NPM_HASDEPLOYMENT: "${{inputs.npm_hasdeployment}}"
        shell: "pwsh"
        run: |
          deno run --allow-env --allow-read --allow-write --no-prompt --quiet 'https://raw.githubusercontent.com/hugoalh/hugoalh/main/.github/workflows/toolbox/review-deno-code/analyze-repository.ts'
      - name: "Verify Code"
        id: "verify-code"
        env:
          INPUT_FILES: "${{steps.analyze-repository.outputs.files}}"
        shell: "pwsh"
        run: |
          [Boolean]$ShouldReload = $Env:GITHUB_EVENT_NAME -iin @('schedule')
          [Boolean]$IsFail = $False
          ForEach ($File In (
            $Env:INPUT_FILES |
              ConvertFrom-Json -Depth 100
          )) {
            Try {
              $ShouldReload ? (deno cache --reload $File) : (deno cache $File)
            }
            Catch {
              $IsFail = $True
            }
            $LASTEXITCODE = 0
          }
          If ($IsFail) {
            Exit 1
          }
      - name: "Verify JSR Package Metadata"
        if: "${{!cancelled() && !inputs.issub && inputs.jsr_hasdeployment}}"
        shell: "pwsh"
        run: |
          deno publish --allow-dirty --config jsr.jsonc --dry-run --no-provenance --token 'ThisIsATokenPlaceholder'
      - name: "Lint Code"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success'}}"
        run: |
          deno lint
      - name: "Test Code"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success' && steps.analyze-repository.outputs.test_dispatch == 'true'}}"
        run: |
          deno test --allow-all --coverage --no-prompt
      - name: "List Test Code Coverage"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success' && steps.analyze-repository.outputs.test_dispatch == 'true'}}"
        run: |
          deno coverage
      - name: "Benchmark Code"
        if: "${{!cancelled() && steps.verify-code.outcome == 'success' && steps.analyze-repository.outputs.benchmark_dispatch == 'true'}}"
        run: |
          deno bench --allow-all --no-prompt
      - name: "Check Dependencies Update"
        if: "${{!cancelled() && !inputs.issub && steps.verify-code.outcome == 'success' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')}}"
        env:
          INPUT_FILES: "${{steps.analyze-repository.outputs.files}}"
        shell: "pwsh"
        run: |
          [String]$Output = deno run --allow-net "--allow-read=$($Env:GITHUB_WORKSPACE)" --no-prompt https://deno.land/x/udd@0.8.2/main.ts --dry-run **/*.ts **/*.tsx deno.jsonc |
            Join-String -Separator "`n"
          $LASTEXITCODE = 0
          Write-Host -Object $Output
          If ($Output -imatch 'able to update') {
            Exit 1
          }
      - name: "Save Deno Cache"
        if: "${{!cancelled() && steps.restore-deno-cache.outcome == 'success'}}"
        uses: "actions/cache/save@v4.0.2"
        with:
          key: "Deno/${{runner.os}}-${{github.run_id}}-${{github.run_attempt}}-${{github.job}}"
          path: "${{env.DENO_DIR}}"
