# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[Call] NodeJS - Code Review (@0)"
on:
  workflow_call:
    inputs:
      runs-on:
        type: "string"
        description: "{string} Type of the machine to run the job on."
        required: false
        default: "ubuntu-latest"
permissions:
  contents: "read"
jobs:
  main:
    name: "Main"
    runs-on: "${{inputs.runs-on}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.1"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v4.0.1"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0"
        with:
          version: "^2.1.0"
      - name: "Resolve NPM Cache Path"
        id: "resolve-cache-path"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$NpmCachePath = npm config get cache |
            Join-String -Separator "`n"
          Set-GitHubActionsOutput -Name 'npm' -Value $NpmCachePath
        shell: "pwsh"
      - name: "Restore NPM Cache"
        id: "restore-cache"
        uses: "actions/cache/restore@v4.0.0"
        with:
          key: "NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}-${{runner.os}}"
          path: "${{steps.resolve-cache-path.outputs.npm}}"
          restore-keys: |-
            NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}-
            NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}
            NPM/${{github.run_id}}-${{github.run_attempt}}-
            NPM/${{github.run_id}}-${{github.run_attempt}}
            NPM/${{github.run_id}}-
            NPM/${{github.run_id}}
            NPM/
      - name: "Verify Dependencies"
        id: "verify-dependencies"
        run: |
          npm install
        shell: "pwsh"
      - name: "Lint Code"
        if: "${{!cancelled() && steps.verify-dependencies.outcome == 'success'}}"
        run: |
          npm run lint
        shell: "pwsh"
      - name: "Save NPM Cache"
        if: "${{!cancelled() && steps.restore-cache.outcome == 'success'}}"
        uses: "actions/cache/save@v4.0.0"
        with:
          key: "NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}-${{runner.os}}"
          path: "${{steps.resolve-cache-path.outputs.npm}}"
