# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Publish NPM (@0)"
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: "{string} NPM token."
        required: true
jobs:
  main:
    name: "Main"
    permissions:
      contents: "write"
      id-token: "write"
    runs-on: "ubuntu-latest"
    env:
      INPUT_RELEASETAG: "${{github.event.release.tag_name}}"
      NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.1"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v4.0.1"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0"
        with:
          version: "^2.1.0"
      - name: "Resolve NPM Cache Path"
        id: "resolve-cache-path"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$NpmCachePath = npm config get cache |
            Join-String -Separator "`n"
          Set-GitHubActionsOutput -Name 'npm' -Value $NpmCachePath
        shell: "pwsh"
      - name: "Restore NPM Cache"
        id: "restore-cache"
        uses: "actions/cache/restore@v4.0.0"
        with:
          key: "NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}-${{runner.os}}"
          path: "${{steps.resolve-cache-path.outputs.npm}}"
          restore-keys: |-
            NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}-
            NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}
            NPM/${{github.run_id}}-${{github.run_attempt}}-
            NPM/${{github.run_id}}-${{github.run_attempt}}
            NPM/${{github.run_id}}-
            NPM/${{github.run_id}}
            NPM/
      - name: "Resolve Package"
        id: "resolve-package"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [PSCustomObject]$Manifest = Get-Content -LiteralPath (Join-Path -Path $Env:GITHUB_WORKSPACE -ChildPath 'package.json') -Raw -Encoding 'UTF8NoBOM' |
            ConvertFrom-Json -Depth 100
          [SemVer]$ManifestVersion = [SemVer]::Parse($Manifest.version)
          [SemVer]$ReleaseVersion = [SemVer]::Parse(($Env:INPUT_RELEASETAG -ireplace '^v', ''))
          If ($ReleaseVersion -ine $ManifestVersion) {
            Write-GitHubActionsWarning -Message "The manifest version ``$($ManifestVersion.ToString())`` is not match the release version ``$($ReleaseVersion.ToString())``! Will apply hot fix."
            npm version $ReleaseVersion.ToString()
            $ManifestVersion = $ReleaseVersion
          }
          [String]$Name = $Manifest.Name
          [Boolean]$VersionIsPreRelease = $Null -ine $ManifestVersion.PreReleaseLabel
          [Boolean]$TagLatest = !$VersionIsPreRelease
          [Boolean]$TagPre = $True
          Try {
            [PSCustomObject]$ManifestRegistry = npm show $Name --json |
              Join-String -Separator "`n" |
              ConvertFrom-Json -Depth 100
            If ($LASTEXITCODE -ne 0) {
              Throw 'Package not found!'
            }
            If ($ManifestVersion -ile [SemVer]::Parse(($ManifestRegistry.'dist-tags'.latest ?? '0.0.0'))) {
              $TagLatest = $False
            }
            If ($ManifestVersion -ile [SemVer]::Parse(($ManifestRegistry.'dist-tags'.pre ?? '0.0.0'))) {
              $TagPre = $False
            }
          }
          Catch {
            Write-Warning -Message "Unable to resolve package: $_"
            $LASTEXITCODE = 0
          }
          [String[]]$Tags = @()
          If ($TagLatest) {
            $Tags += 'latest'
          }
          If ($TagPre) {
            $Tags += 'pre'
          }
          If (!$VersionIsPreRelease) {
            $Tags += "latest-$($ManifestVersion.Major)"
          }
          $Tags += "pre-$($ManifestVersion.Major)"
          If ($Tags.Count -eq 0) {
            Write-GitHubActionsFail -Message 'No available tags!'
          }
          Set-GitHubActionsOutput -Name 'name' -Value $Name
          Set-GitHubActionsOutput -Name 'version' -Value $ManifestVersion.ToString()
          Set-GitHubActionsOutput -Name 'descriptor' -Value "$($Name)@$($ManifestVersion.ToString())"
          Set-GitHubActionsOutput -Name 'build' -Value ($Null -ne $Manifest.scripts.'build').ToString().ToLower()
          Set-GitHubActionsOutput -Name 'tags_first' -Value $Tags[0]
          Set-GitHubActionsOutput -Name 'tags_rest' -Value (
            $Tags |
              Select-Object -SkipIndex 0 |
              Join-String -Separator ','
          )
          Set-GitHubActionsOutput -Name 'tarballname' -Value "$($Name -ireplace '^@', '' -ireplace '\/', '-')-$($ManifestVersion.ToString()).tgz"
        shell: "pwsh"
      - name: "Install Dependencies"
        run: |
          npm install
      - name: "Build Package"
        if: "${{steps.resolve-package.outputs.build == 'true'}}"
        run: |
          npm run build
      - name: "Publish Package With Tag `${{steps.resolve-package.outputs.tags_first}}` (Provenance)"
        id: "publish-provenance"
        run: |
          npm publish --provenance --tag $Env:INPUT_TAGSFIRST
        shell: "pwsh"
        env:
          INPUT_TAGSFIRST: "${{steps.resolve-package.outputs.tags_first}}"
      - name: "Publish Package With Tag `${{steps.resolve-package.outputs.tags_first}}`"
        if: "${{!cancelled() && steps.publish-provenance.outcome == 'failure'}}"
        id: "publish-raw"
        run: |
          npm publish --tag $Env:INPUT_TAGSFIRST
        shell: "pwsh"
        env:
          INPUT_TAGSFIRST: "${{steps.resolve-package.outputs.tags_first}}"
      - name: "Publish Package With Rest Tags"
        if: "${{!cancelled() && (steps.publish-provenance.outcome == 'success' || steps.publish-raw.outcome == 'success') && steps.resolve.outputs.tags_rest != ''}}"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$PackageDescriptor = $Env:INPUT_DESCRIPTOR
          [String[]]$PackageTagsRest = $Env:INPUT_TAGSREST -isplit ','
          ForEach ($PackageTagRest In $PackageTagsRest) {
            Try {
              npm dist-tag add $PackageDescriptor $PackageTagRest
            }
            Catch {
              Write-GitHubActionsError -Message $_
            }
          }
        shell: "pwsh"
        env:
          INPUT_DESCRIPTOR: "${{steps.resolve-package.outputs.descriptor}}"
          INPUT_TAGSREST: "${{steps.resolve-package.outputs.tags_rest}}"
      - name: "Pack & Upload Package `${{steps.resolve-package.outputs.tarballname}}` To GitHub Release Tag `${{env.INPUT_RELEASETAG}}`"
        if: "${{!cancelled() && steps.resolve-package.outcome == 'success'}}"
        run: |
          npm pack
          gh release upload $Env:INPUT_RELEASETAG $Env:INPUT_TARBALLNAME --clobber --repo $Env:GITHUB_REPOSITORY
        shell: "pwsh"
        env:
          GH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          INPUT_TARBALLNAME: "${{steps.resolve-package.outputs.tarballname}}"
      - name: "Save NPM Cache"
        if: "${{!cancelled() && steps.restore-cache.outcome == 'success'}}"
        uses: "actions/cache/save@v4.0.0"
        with:
          key: "NPM/${{github.run_id}}-${{github.run_attempt}}-${{github.job}}-${{runner.os}}"
          path: "${{steps.resolve-cache-path.outputs.npm}}"
