# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Sync Labels (@0)"
on:
  workflow_call:
jobs:
  main:
    name: "Main"
    permissions:
      contents: "read"
      issues: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.2.0"
      - name: "Sync Labels"
        uses: "EndBug/label-sync@v2.3.3"
        with:
          config-file: ".github/labels.yml"
          delete-other-labels: "true"
