# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] Publish PowerShell Module (@0)"
on:
  workflow_call:
    inputs:
      builder:
        type: "string"
        description: "{String} Builder of the PowerShell module."
        required: false
      context:
        type: "string"
        description: "{String} Context of the PowerShell module."
        required: false
        default: ".\\"
    secrets:
      POWERSHELLGALLERY_TOKEN:
        description: "{String} PowerShell Gallery token."
        required: true
jobs:
  publish:
    name: "Publish"
    permissions:
      contents: "write"
    runs-on: "windows-latest"
    env:
      INPUT_BUILDER: "${{inputs.builder}}"
      INPUT_CONTEXT: "${{inputs.context}}"
      INPUT_TOKEN: "${{secrets.POWERSHELLGALLERY_TOKEN}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Setup PowerShell Environment"
        shell: "pwsh"
        run: |-
          $PSRepositoryPSGalleryMeta = Get-PSRepository -Name 'PSGallery'
          If ($PSRepositoryPSGalleryMeta.InstallationPolicy -ine 'Trusted') {
            Write-Host -Object 'Tweak PowerShell repository configuration.'
            Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted' -Verbose
          }
      - name: "Analyze Repository"
        id: "analyze-repository"
        shell: "pwsh"
        run: |-
          $ManifestsPath = Get-ChildItem -LiteralPath $Env:INPUT_CONTEXT -Filter '*.psd1' -File
          If ($ManifestsPath.Count -ne 1) {
            Write-Host -Object "::error::Invalid manifest count! Expect ``1``; Current ``$($ManifestsPath.Count)``."
            Exit 1
          }
          [String]$ManifestPath = $ManifestsPath.FullName
          $ManifestFromTest = Test-ModuleManifest -Path $ManifestPath -Verbose
          $ManifestFromData = Import-PowerShellDataFile -LiteralPath $ManifestPath -SkipLimitCheck
          [String]$Name = $ManifestFromTest.Name
          [String]$Version = $ManifestFromData.ModuleVersion
          If ($Null -ine $ManifestFromData.PrivateData.PSData.Prerelease) {
            $Version += "-$($ManifestFromData.PrivateData.PSData.Prerelease)"
          }
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "ballname=$($Name.ToLower()).$($Version).nupkg" -Confirm:$False -Encoding 'UTF8NoBOM'
      - name: "Build Package"
        if: "${{inputs.builder != ''}}"
        shell: "pwsh"
        run: |-
          . ".\$($Env:INPUT_BUILDER)"
      - name: "Publish Package To PowerShell Gallery"
        shell: "pwsh"
        run: |-
          Publish-Module -Path $Env:INPUT_CONTEXT -NugetAPIKey $Env:INPUT_TOKEN -Force -Verbose
    outputs:
      package_ballname: "${{steps.analyze-repository.outputs.ballname}}"
  await:
    name: "Await"
    needs:
      - "publish"
    if: "${{needs.publish.result == 'success'}}"
    permissions: {}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Wait For PowerShell Gallery Update"
        shell: "pwsh"
        run: |-
          Start-Sleep -Seconds 120
  assets:
    name: "Assets"
    needs:
      - "await"
      - "publish"
    if: "${{needs.await.result == 'success'}}"
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Upload Package `${{needs.publish.outputs.package_ballname}}` To GitHub Release Tag ${{github.event.release.tag_name}}"
        env:
          GH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          INPUT_PACKAGEBALLNAME: "${{needs.publish.outputs.package_ballname}}"
          INPUT_RELEASETAG: "${{github.event.release.tag_name}}"
        shell: "pwsh"
        run: |-
          Invoke-WebRequest -Uri "https://psg-prod-eastus.azureedge.net/packages/$($Env:INPUT_PACKAGEBALLNAME)" -MaximumRedirection 1 -MaximumRetryCount 5 -RetryIntervalSec 5 -Method 'GET' -OutFile $Env:INPUT_PACKAGEBALLNAME
          gh release upload $Env:INPUT_RELEASETAG $Env:INPUT_PACKAGEBALLNAME --clobber --repo $Env:GITHUB_REPOSITORY
