# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[CALL] OSSAR Analysis (@0)"
on:
  workflow_call:
jobs:
  main:
    name: "Main"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.1"
      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v4.0.0"
        with:
          dotnet-version: "3.1.x"
      - name: "Analyze Repository"
        id: "ossar"
        uses: "github/ossar-action@v1.1.0"
      - name: "Upload Analysis Result"
        uses: "github/codeql-action/upload-sarif@v3.24.3"
        with:
          sarif_file: "${{steps.ossar.outputs.sarifFile}}"
