# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "CI/CD - Deno (Reusable Workflow)"
on:
  workflow_call:
defaults:
  run:
    shell: "pwsh"
jobs:
  benchmark:
    name: "Benchmark"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Dispatcher"
        id: "dispatcher"
        run: |
          [String[]]$Files = Get-ChildItem -LiteralPath $Env:GITHUB_WORKSPACE -Include @('*_bench.[jt]s', '*_bench.[jt]sx', '*_bench.m[jt]s', '*.bench.[jt]s', '*.bench.[jt]sx', '*.bench.m[jt]s', 'bench.[jt]s', 'bench.[jt]sx', 'bench.m[jt]s') -Recurse -File |
            Select-Object -ExpandProperty 'FullName'
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "dispatch=$(($Files.Count -gt 0).ToString().ToLower())"
      - name: "Setup Deno"
        if: "${{steps.dispatcher.outputs.dispatch == 'true'}}"
        uses: "denoland/setup-deno@v1.1.2"
        with:
          deno-version: "^1.36.1"
      - name: "Benchmark Code"
        if: "${{steps.dispatcher.outputs.dispatch == 'true'}}"
        run: |
          deno bench
  check-dependencies-update:
    name: "Check Dependencies Update"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1.1.2"
        with:
          deno-version: "^1.36.1"
      - name: "Check Dependencies Update"
        id: "check-dependencies-update"
        run: |
          [String[]]$Files = Get-ChildItem -LiteralPath $Env:GITHUB_WORKSPACE -Include @('*.[jt]s', '*.[jt]sx', '*.m[jt]s') -Recurse -File |
            Select-Object -ExpandProperty 'FullName'
          [Boolean]$IsFail = $False
          ForEach ($File In $Files) {
            [String]$Output =  deno run --allow-net --allow-read="$Env:GITHUB_WORKSPACE" --no-prompt https://deno.land/x/udd/main.ts --dry-run $File |
              Join-String -Separator "`n"
            If ($Output -imatch 'able to update') {
              $IsFail = $True
            }
            Write-Host -Object $Output
          }
          If ($IsFail) {
            Exit 1
          }
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Dispatcher"
        id: "dispatcher"
        run: |
          [String[]]$Files = Get-ChildItem -LiteralPath $Env:GITHUB_WORKSPACE -Include @('*_test.[jt]s', '*_test.[jt]sx', '*_test.m[jt]s', '*.test.[jt]s', '*.test.[jt]sx', '*.test.m[jt]s', 'test.[jt]s', 'test.[jt]sx', 'test.m[jt]s') -Recurse -File |
            Select-Object -ExpandProperty 'FullName'
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "dispatch=$(($Files.Count -gt 0).ToString().ToLower())"
      - name: "Setup Deno"
        if: "${{steps.dispatcher.outputs.dispatch == 'true'}}"
        uses: "denoland/setup-deno@v1.1.2"
        with:
          deno-version: "^1.36.1"
      - name: "Test Code"
        if: "${{steps.dispatcher.outputs.dispatch == 'true'}}"
        id: "test"
        run: |
          deno test --no-check
  verify-dependencies:
    name: "Verify Dependencies"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v1.1.2"
        with:
          deno-version: "^1.36.1"
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Verify Dependencies"
        id: "verify-dependencies"
        run: |
          deno vendor mod.ts
