name: "Happy Birthday"
on:
  schedule:
    - cron: "0 12 25 11 *"
jobs:
  discord-english:
    name: "Discord (English)"
    runs-on: "ubuntu-latest"
    steps:
      - id: "discord-english-main"
        uses: "hugoalh/GitHubAction.SendToDiscord@v3.0.0"
        with:
          configuration: ".github/workflows_configuration/happy-birthday-send-to-discord.yml"
          webhook_id: "${{secrets.DISCORD_WEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_BIRTHDAYCAKE_ID}}"
          webhook_token: "${{secrets.DISCORD_WEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_BIRTHDAYCAKE_TOKEN}}"
          variable_join: "."
          # variable_list_external:
          variable_prefix: "%"
          variable_suffix: "%"
  ifttt-english:
    name: "IFTTT (English)"
    runs-on: "ubuntu-latest"
    steps:
      - id: "ifttt-english-main"
        uses: "hugoalh/GitHubAction.SendToIFTTT@v3.0.0"
        with:
          webhook_eventname: "githubaction_twitter"
          webhook_key: "${{secrets.IFTTT_WEBHOOK_HUGOALH_KEY}}"
          variable_join: "."
          # variable_list_external:
          variable_prefix: "%"
          variable_suffix: "%"
          value1: "🎉 Happy birthday, hugoalh! 🎂"
          # value2:
          # value3:
