name: "Publish PowerShell Module - PowerShell Gallery (Reusable Workflow)"
on:
  workflow_call:
    inputs:
      path:
        type: "string"
        description: "{String} PowerShell module root."
        required: false
        default: ".\\"
    secrets:
      POWERSHELLGALLERY_TOKEN:
        description: "{String} PowerShell Gallery token."
        required: true
defaults:
  run:
    shell: "pwsh"
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Setup PowerShell Environment"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.4.0"
        with:
          version: "^1.6.0"
      - name: "Test Publish"
        run: |
          Publish-Module -Path '${{inputs.path}}' -NugetAPIKey 'GUID' -WhatIf -Verbose
      - name: "Publish"
        run: |
          Publish-Module -Path '${{inputs.path}}' -NugetAPIKey '${{secrets.POWERSHELLGALLERY_TOKEN}}' -Verbose
  main-fallback:
    name: "Main (Fallback)"
    needs:
      - "main"
    if: "${{needs.main.result == 'failure'}}"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Setup PowerShell Environment"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.4.0"
        with:
          version: "^1.6.0"
      - name: "Test Publish"
        run: |
          Publish-Module -Path '${{inputs.path}}' -NugetAPIKey 'GUID' -WhatIf -Verbose
      - name: "Publish"
        run: |
          Publish-Module -Path '${{inputs.path}}' -NugetAPIKey '${{secrets.POWERSHELLGALLERY_TOKEN}}' -Verbose
