name: "Publish NodeJS Package - NPM (Reusable Workflow)"
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: "{string} NPM token."
        required: true
defaults:
  run:
    shell: "pwsh"
env:
  NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
permissions:
  actions: "write"
  checks: "write"
  contents: "write"
  deployments: "write"
  discussions: "write"
  id-token: "write"
  issues: "write"
  packages: "write"
  pages: "write"
  pull-requests: "write"
  repository-projects: "write"
  security-events: "write"
  statuses: "write"
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v3.7.0"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Setup NPM"
        run: |
          npm --global install npm@latest
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.3.0"
        with:
          toolkit_version: "1.6.0-beta4"
          toolkit_allowprerelease: "True"
      - name: "Get Package Meta"
        id: "get-package-meta"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [PSCustomObject]$EventPayload = Get-GitHubActionsWebhookEventPayload
          [PSCustomObject]$PackageMeta = Get-Content -LiteralPath (Join-Path -Path $Env:GITHUB_WORKSPACE -ChildPath 'package.json') -Raw -Encoding 'UTF8NoBOM' |
            ConvertFrom-Json -Depth 100
          [SemVer]$PackageVersionCurrent = [SemVer]::Parse($PackageMeta.version)
          [Boolean]$PackageVersionIsPreRelease = $Null -ine $PackageVersionCurrent.PreReleaseLabel
          [Boolean]$PackageTagLatest = !$PackageVersionIsPreRelease
          [Boolean]$PackageTagPre = $True
          [String[]]$PackageDevDependencies = $PackageMeta.devDependencies.PSObject.Properties.Name ?? @()
          [String]$PackageTarballName = "$($PackageMeta.name -ireplace '^@', '' -ireplace '\/', '-')-$($PackageMeta.version).tgz"
          Try {
            [PSCustomObject]$PackageRegistry = Invoke-WebRequest -Uri "https://registry.npmjs.org/$($PackageMeta.name)" -Headers @{ 'Content-Type' = 'application/json' } -MaximumRedirection 1 -MaximumRetryCount 2 -RetryIntervalSec 5 -Method 'Get' |
              Select-Object -ExpandProperty 'Content' |
              ConvertFrom-Json -Depth 100
            If ($LASTEXITCODE -ine 0) {
              Throw 'Most likely this is a new package.'
            }
            If ($PackageVersionCurrent -ile [SemVer]::Parse($PackageRegistry.'dist-tags'.latest ?? '0.0.0')) {
              $PackageTagLatest = $False
            }
            If ($PackageVersionCurrent -ile [SemVer]::Parse($PackageRegistry.'dist-tags'.pre ?? '0.0.0')) {
              $PackageTagPre = $False
            }
          }
          Catch {
            Write-Warning -Message "Unable to analysis package ``dist-tags``: $_"
          }
          [String[]]$PackageTags = @("pre-$($PackageVersionCurrent.Major)")
          If ($PackageTagLatest -or !$PackageVersionIsPreRelease) {
            $PackageTags += "latest-$($PackageVersionCurrent.Major)"
          }
          [Boolean]$BuildDistribution = 'typescript' -iin $PackageDevDependencies -and !(Test-Path -LiteralPath '.\dist' -PathType 'Container') -and (Test-Path -LiteralPath '.\src' -PathType 'Container') -and (Test-Path -LiteralPath '.\tsconfig.json' -PathType 'Leaf')
          [Boolean]$BuildTarball = $PackageTarballName -inotin (
            $EventPayload.release.assets |
              Select-Object -ExpandProperty 'name'
          )
          Set-GitHubActionsOutput -Name 'descriptor' -Value "$($PackageMeta.name)@$($PackageMeta.version)"
          Set-GitHubActionsOutput -Name 'tag_latest' -Value $PackageTagLatest.ToString().ToLower()
          Set-GitHubActionsOutput -Name 'tag_pre' -Value $PackageTagPre.ToString().ToLower()
          Set-GitHubActionsOutput -Name 'tags' -Value (
            $PackageTags |
              Sort-Object -Unique |
              Join-String -Separator ';'
          )
          Set-GitHubActionsOutput -Name 'tarballname' -Value $PackageTarballName
          Set-GitHubActionsOutput -Name 'build_distribution' -Value $BuildDistribution.ToString().ToLower()
          Set-GitHubActionsOutput -Name 'build_tarball' -Value $BuildTarball.ToString().ToLower()
          Set-GitHubActionsOutput -Name 'release_assetsuploadurl' -Value ($EventPayload.release.upload_url -ireplace '\{.+?\}$', '')
      - name: "Setup PNPM"
        if: "${{steps.get-package-meta.outputs.build_distribution == 'true' || steps.get-package-meta.outputs.build_tarball == 'true'}}"
        run: |
          npm --global install pnpm
      - name: "Build Distribution"
        if: "${{steps.get-package-meta.outputs.build_distribution == 'true'}}"
        run: |
          pnpm install
          $TscPath = Resolve-Path -LiteralPath '.\node_modules\.bin\tsc.ps1'
          $ConfigPath = Resolve-Path -LiteralPath '.\tsconfig.json'
          If (Test-Path -LiteralPath '.\dist') {
            Remove-Item -LiteralPath '.\dist' -Recurse -Force -Confirm:$False
          }
          Invoke-Expression -Command "$($TscPath.Path) -p $($ConfigPath.Path)"
      - name: "Publish (NPM Provenance Beta)"
        id: "publish-npm-provenance-beta"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$PackageDescriptor = '${{steps.get-package-meta.outputs.descriptor}}'
          [Boolean]$PackageTagLatest = [Boolean]::Parse('${{steps.get-package-meta.outputs.tag_latest}}')
          [Boolean]$PackageTagPre = [Boolean]::Parse('${{steps.get-package-meta.outputs.tag_pre}}')
          [String[]]$PackageTags = ('${{steps.get-package-meta.outputs.tags}}' -isplit ';') + @('publish')
          If ($PackageTagLatest) {
            npm publish --provenance
            Invoke-Expression -Command "npm dist-tag add `"$PackageDescriptor`" pre"
          }
          ElseIf ($PackageTagPre) {
            npm publish --provenance --tag pre
          }
          Else {
            [String]$Tag = $PackageTags |
              Select-Object -First 1
            $PackageTags = $PackageTags |
              Where-Object -FilterScript { $_ -ine $Tag }
            Invoke-Expression -Command "npm publish --provenance --tag `"$Tag`""
          }
          ForEach ($Tag In $PackageTags) {
            Try {
              Invoke-Expression -Command "npm dist-tag add `"$PackageDescriptor`" `"$Tag`""
            }
            Catch {
              Write-GitHubActionsError -Message $_
            }
          }
        continue-on-error: true
      - name: "Publish"
        if: "${{steps.publish-npm-provenance-beta.outcome != 'success'}}"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$PackageDescriptor = '${{steps.get-package-meta.outputs.descriptor}}'
          [Boolean]$PackageTagLatest = [Boolean]::Parse('${{steps.get-package-meta.outputs.tag_latest}}')
          [Boolean]$PackageTagPre = [Boolean]::Parse('${{steps.get-package-meta.outputs.tag_pre}}')
          [String[]]$PackageTags = ('${{steps.get-package-meta.outputs.tags}}' -isplit ';') + @('publish')
          If ($PackageTagLatest) {
            npm publish
            Invoke-Expression -Command "npm dist-tag add `"$PackageDescriptor`" pre"
          }
          ElseIf ($PackageTagPre) {
            npm publish --tag pre
          }
          Else {
            [String]$Tag = $PackageTags |
              Select-Object -First 1
            $PackageTags = $PackageTags |
              Where-Object -FilterScript { $_ -ine $Tag }
            Invoke-Expression -Command "npm publish --tag `"$Tag`""
          }
          ForEach ($Tag In $PackageTags) {
            Try {
              Invoke-Expression -Command "npm dist-tag add `"$PackageDescriptor`" `"$Tag`""
            }
            Catch {
              Write-GitHubActionsError -Message $_
            }
          }
      - name: "Build & Upload Tarball To GitHub Release"
        if: "${{steps.get-package-meta.outputs.build_tarball == 'true'}}"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          pnpm pack
          Try {
            Invoke-WebRequest -Uri "${{steps.get-package-meta.outputs.release_assetsuploadurl}}?name=$([Uri]::EscapeDataString('${{steps.get-package-meta.outputs.tarballname}}'))" -Headers @{
              Accept = 'application/vnd.github+json'
              Authorization = 'Bearer ${{github.token}}'
              'Content-Type' = 'application/gzip'
              'User-Agent' = $Env:GITHUB_WORKFLOW_REF
              'X-GitHub-Api-Version' = '2022-11-28'
            } -Method 'Post' -InFile '.\${{steps.get-package-meta.outputs.tarballname}}' -SkipHeaderValidation
          }
          Catch {
            Write-GitHubActionsError -Message "Unable to upload assets tarball: $_"
          }
