name: "Publish PowerShell Module - PowerShell Gallery (Reusable Workflow)"
on:
  workflow_call:
    inputs:
      path:
        type: "string"
        description: "{String} PowerShell module root."
        required: false
        default: ".\\"
    secrets:
      POWERSHELLGALLERY_TOKEN:
        description: "{String} PowerShell Gallery token."
        required: true
defaults:
  run:
    shell: "pwsh"
jobs:
  publish-powershell-module-psg:
    name: "Publish PowerShell Module - PowerShell Gallery"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.2"
      - name: "Setup PowerShell Environment"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.2.3"
        with:
          toolkit_setup: "false"
      - name: "Test Publish"
        run: |
          Publish-Module -Path '${{inputs.path}}' -NugetAPIKey 'GUID' -WhatIf -Verbose
      - name: "Publish"
        run: |
          Publish-Module -Path '${{inputs.path}}' -NugetAPIKey '${{secrets.POWERSHELLGALLERY_TOKEN}}' -Verbose
