# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[Reusable] Publish NodeJS Package - NPM"
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: "{string} NPM token."
        required: true
defaults:
  run:
    shell: "pwsh"
env:
  INPUT_RELEASETAG: "${{github.event.release.tag_name}}"
  NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
permissions:
  actions: "write"
  checks: "write"
  contents: "write"
  deployments: "write"
  id-token: "write"
  security-events: "write"
  statuses: "write"
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.0"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v3.8.1"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.6.0"
        with:
          version: "^1.7.2"
      - name: "Resolve Package"
        id: "resolve"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [PSCustomObject]$PackageMetaLocal = Get-Content -LiteralPath (Join-Path -Path $Env:GITHUB_WORKSPACE -ChildPath 'package.json') -Raw -Encoding 'UTF8NoBOM' |
            ConvertFrom-Json -Depth 100
          [SemVer]$PackageMetaLocalVersion = [SemVer]::Parse($PackageMetaLocal.version)
          [SemVer]$PackageMetaReleaseVersion = [SemVer]::Parse(($Env:INPUT_RELEASETAG -ireplace '^v', ''))
          If ($PackageMetaReleaseVersion -ine $PackageMetaLocalVersion) {
            Write-GitHubActionsWarning -Message "The local version ``$($PackageMetaLocalVersion.ToString())`` is not match the release version ``$($PackageMetaReleaseVersion.ToString())``! Will apply hot fix."
            npm version $PackageMetaReleaseVersion.ToString()
            $PackageMetaLocalVersion = $PackageMetaReleaseVersion
          }
          [String]$PackageName = $PackageMetaLocal.Name
          [String]$PackageTarballName = "$($PackageName -ireplace '^@', '' -ireplace '\/', '-')-$($PackageMetaLocalVersion.ToString()).tgz"
          [String[]]$PackageMetaLocalDevDependencies = $PackageMetaLocal.devDependencies.PSObject.Properties.Name ?? @()
          [Boolean]$PackageNeedBuild = 'typescript' -iin $PackageMetaLocalDevDependencies -and !(Test-Path -LiteralPath '.\dist' -PathType 'Container') -and (Test-Path -LiteralPath '.\src' -PathType 'Container') -and (Test-Path -LiteralPath '.\tsconfig.json' -PathType 'Leaf')
          [Boolean]$PackageTagLatest = $Null -ieq $PackageMetaLocalVersion.PreReleaseLabel
          [Boolean]$PackageTagPre = $True
          Try {
            [PSCustomObject]$PackageMetaRegistry = npm show $PackageName --json |
              Join-String -Separator "`n" |
              ConvertFrom-Json -Depth 100
            If ($LASTEXITCODE -ne 0) {
              Throw 'Package not found!'
            }
            If ($PackageMetaLocalVersion -ile [SemVer]::Parse(($PackageMetaRegistry.'dist-tags'.latest ?? '0.0.0'))) {
              $PackageTagLatest = $False
            }
            If ($PackageMetaLocalVersion -ile [SemVer]::Parse(($PackageMetaRegistry.'dist-tags'.pre ?? '0.0.0'))) {
              $PackageTagPre = $False
            }
          }
          Catch {
            Write-Warning -Message "Unable to analysis package: $_"
          }
          [String[]]$PackageTags = @()
          If ($PackageTagLatest) {
            $PackageTags += 'latest'
          }
          If ($PackageTagPre) {
            $PackageTags += 'pre'
          }
          $PackageTags += "latest-$($PackageMetaLocalVersion.Major)"
          $PackageTags += "pre-$($PackageMetaLocalVersion.Major)"
          $PackageTags += 'publish'
          If ($PackageTags.Count -eq 0) {
            Write-GitHubActionsFail -Message 'No available tags!'
          }
          [String]$PackageTagsFirst = $PackageTags[0]
          [String[]]$PackageTagsRest = (
            $PackageTags |
              Select-Object -SkipIndex 0
          ) ?? @()
          Set-GitHubActionsOutput -Name 'name' -Value $PackageName
          Set-GitHubActionsOutput -Name 'version' -Value $PackageMetaLocalVersion.ToString()
          Set-GitHubActionsOutput -Name 'descriptor' -Value "$($PackageName)@$($PackageMetaLocalVersion.ToString())"
          Set-GitHubActionsOutput -Name 'tags_first' -Value $PackageTagsFirst
          Set-GitHubActionsOutput -Name 'tags_rest' -Value (
            $PackageTagsRest |
              Join-String -Separator ';'
          )
          Set-GitHubActionsOutput -Name 'tarballname' -Value $PackageTarballName
          Set-GitHubActionsOutput -Name 'build' -Value $PackageNeedBuild.ToString().ToLower()
      - name: "Build Package"
        if: "${{steps.resolve.outputs.build == 'true'}}"
        run: |
          npm install
          $TscPath = Resolve-Path -LiteralPath '.\node_modules\.bin\tsc.ps1'
          $ConfigPath = Resolve-Path -LiteralPath '.\tsconfig.json'
          If (Test-Path -LiteralPath '.\dist') {
            Remove-Item -LiteralPath '.\dist' -Recurse -Force -Confirm:$False
          }
          . $TscPath.Path -p $ConfigPath.Path
      - name: "Publish With Tag ${{steps.resolve.outputs.tags_first}} (Provenance)"
        id: "publish-provenance"
        run: |
          [String]$PackageTagsFirst = $Env:INPUT_TAGSFIRST
          npm publish --provenance --tag $PackageTagsFirst
        env:
          INPUT_TAGSFIRST: "${{steps.resolve.outputs.tags_first}}"
      - name: "Publish With Tag ${{steps.resolve.outputs.tags_first}}"
        if: "${{steps.publish-provenance.outcome == 'failure'}}"
        id: "publish"
        run: |
          [String]$PackageTagsFirst = $Env:INPUT_TAGSFIRST
          npm publish --tag $PackageTagsFirst
        env:
          INPUT_TAGSFIRST: "${{steps.resolve.outputs.tags_first}}"
      - name: "Publish With Rest Tags"
        if: "${{(steps.publish-provenance.outcome == 'success' || steps.publish.outcome == 'success') && steps.resolve.outputs.tags_rest != ''}}"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [String]$PackageDescriptor = $Env:INPUT_DESCRIPTOR
          [String[]]$PackageTagsRest = $Env:INPUT_TAGSREST -isplit ';'
          ForEach ($PackageTagRest In $PackageTagsRest) {
            Try {
              npm dist-tag add $PackageDescriptor $PackageTagRest
            }
            Catch {
              Write-GitHubActionsError -Message $_
            }
          }
        env:
          INPUT_DESCRIPTOR: "${{steps.resolve.outputs.descriptor}}"
          INPUT_TAGSREST: "${{steps.resolve.outputs.tags_rest}}"
      - name: "Pack & Upload Tarball `${{steps.resolve.outputs.tarballname}}` To GitHub Release Tag ${{env.INPUT_RELEASETAG}}"
        if: "${{!cancelled() && steps.resolve.outcome == 'success'}}"
        run: |
          npm pack
          gh release upload $Env:INPUT_RELEASETAG $Env:INPUT_TARBALLNAME --clobber --repo $Env:GITHUB_REPOSITORY
        env:
          GH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          INPUT_TARBALLNAME: "${{steps.resolve.outputs.tarballname}}"
