# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[Reusable] Announce New Release - Discord"
on:
  workflow_call:
    inputs:
      payload:
        type: "string"
        description: "{object} JSON/YAML/YML payload."
        required: true
    secrets:
      DISCORD_WEBHOOK:
        description: "{string} Discord webhook."
        required: true
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send Discord Webhook"
        uses: "hugoalh/send-discord-webhook-ghaction@v5.0.6"
        with:
          key: "${{secrets.DISCORD_WEBHOOK}}"
          payload: "${{inputs.payload}}"
          wait: "true"
