name: "Secret Manager"
on: "workflow_dispatch"
jobs:
  job1:
    name: "Job 1"
    runs-on: "ubuntu-latest"
    steps:
      - id: "job1-main"
        uses: "hugoalh/GitHubAction.GitHubSecretManager@master"
        with:
          token: "${{secrets.GITHUB_PERSONALACCESSTOKEN_GITHUBSECRETMANAGER}}"
          mode: "pushmerge"
          target: |
            hugoalh/GitHubAction.SendToDiscord
            hugoalh/GitHubAction.SendToIFTTT
            hugoalh/GitHubAction.GitHubSecretManager
          prefix: "ghsm_"
          ghsm_discord_webhook_hugoalhstudio_studioannouncement_newreleaseannouncer_id: "${{secrets.DISCORD_WEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_ID}}"
          ghsm_discord_webhook_hugoalhstudio_studioannouncement_newreleaseannouncer_token: "${{secrets.DISCORD_WEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_TOKEN}"
