name: "Secret Manager"
on: "workflow_dispatch"
jobs:
  job1:
    name: "Job 1"
    runs-on: "ubuntu-latest"
    steps:
      - id: "job1-main"
        uses: "hugoalh/GitHubAction.GitHubSecretManager@master"
        with:
          token: "${{secrets.GITHUBPERSONALACCESSTOKEN_GITHUBSECRETMANAGER}}"
          mode: "pushmerge"
          target: |
            hugoalh/GitHubAction.LanguageList
            hugoalh/GitHubAction.SendToDiscord
            hugoalh/GitHubAction.SendToIFTTT
          prefix: "ghsm_"
          ghsm_discordwebhook_hugoalhstudio_studioannouncement_newreleaseannouncer_id: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_ID}}"
          ghsm_discordwebhook_hugoalhstudio_studioannouncement_newreleaseannouncer_token: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_TOKEN}}"
          ghsm_DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_BIRTHDAYCAKE_ID: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_BIRTHDAYCAKE_ID}}"
          ghsm_DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_BIRTHDAYCAKE_TOKEN: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_BIRTHDAYCAKE_TOKEN}}"
          ghsm_IFTTTWEBHOOK_HUGOALH_KEY: "${{secrets.IFTTTWEBHOOK_HUGOALH_KEY}}"
