name: "Secret Manager"
on: "workflow_dispatch"
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/GitHubAction.GitHubSecretManager@master"
        with:
          token: "${{secrets.GITHUBPERSONALACCESSTOKEN_GITHUBSECRETMANAGER}}"
          mode: "pushmerge"
          target_repository: |
            hugoalh/GitHubAction.*
          target_organization: |
            hugoalh-studio
          prefix: "ghsm_"
          ghsm_discordwebhook_hugoalhstudio_studioannouncement_newreleaseannouncer_id: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_ID}}"
          ghsm_discordwebhook_hugoalhstudio_studioannouncement_newreleaseannouncer_token: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_TOKEN}}"
          ghsm_IFTTTWEBHOOK_HUGOALH_KEY: "${{secrets.IFTTTWEBHOOK_HUGOALH_KEY}}"
