# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Sync Labels (Reusable Workflow)"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
  workflow_call:
  workflow_dispatch:
permissions:
  issues: "write"
  pull-requests: "write"
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Sync Labels"
        uses: "srealmoreno/label-sync-action@v1.0.2"
        with:
          config-file: ".github/labels.yml"
